<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#375EAB">

  <title>src/go/types/under.go - Go Documentation Server</title>

<link type="text/css" rel="stylesheet" href="../../../lib/godoc/style.css">

<script>window.initFuncs = [];</script>
<script src="../../../lib/godoc/jquery.js" defer></script>



<script>var goVersion = "go1.22.2";</script>
<script src="../../../lib/godoc/godocs.js" defer></script>
</head>
<body>

<div id='lowframe' style="position: fixed; bottom: 0; left: 0; height: 0; width: 100%; border-top: thin solid grey; background-color: white; overflow: auto;">
...
</div><!-- #lowframe -->

<div id="topbar" class="wide"><div class="container">
<div class="top-heading" id="heading-wide"><a href="../../../index.html">Go Documentation Server</a></div>
<div class="top-heading" id="heading-narrow"><a href="../../../index.html">GoDoc</a></div>
<a href="under.go#" id="menu-button"><span id="menu-button-arrow">&#9661;</span></a>
<form method="GET" action="http://localhost:8080/search">
<div id="menu">

<span class="search-box"><input type="search" id="search" name="q" placeholder="Search" aria-label="Search" required><button type="submit"><span><!-- magnifying glass: --><svg width="24" height="24" viewBox="0 0 24 24"><title>submit search</title><path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/><path d="M0 0h24v24H0z" fill="none"/></svg></span></button></span>
</div>
</form>

</div></div>



<div id="page" class="wide">
<div class="container">


  <h1>
    Source file
    <a href="http://localhost:8080/src">src</a>/<a href="http://localhost:8080/src/go">go</a>/<a href="http://localhost:8080/src/go/types">types</a>/<span class="text-muted">under.go</span>
  </h1>





  <h2>
    Documentation: <a href="http://localhost:8080/pkg/go/types">go/types</a>
  </h2>



<div id="nav"></div>


<script type='text/javascript'>document.ANALYSIS_DATA = null;</script>
<pre><span id="L1" class="ln">     1&nbsp;&nbsp;</span><span class="comment">// Code generated by &#34;go test -run=Generate -write=all&#34;; DO NOT EDIT.</span>
<span id="L2" class="ln">     2&nbsp;&nbsp;</span>
<span id="L3" class="ln">     3&nbsp;&nbsp;</span><span class="comment">// Copyright 2011 The Go Authors. All rights reserved.</span>
<span id="L4" class="ln">     4&nbsp;&nbsp;</span><span class="comment">// Use of this source code is governed by a BSD-style</span>
<span id="L5" class="ln">     5&nbsp;&nbsp;</span><span class="comment">// license that can be found in the LICENSE file.</span>
<span id="L6" class="ln">     6&nbsp;&nbsp;</span>
<span id="L7" class="ln">     7&nbsp;&nbsp;</span>package types
<span id="L8" class="ln">     8&nbsp;&nbsp;</span>
<span id="L9" class="ln">     9&nbsp;&nbsp;</span><span class="comment">// under returns the true expanded underlying type.</span>
<span id="L10" class="ln">    10&nbsp;&nbsp;</span><span class="comment">// If it doesn&#39;t exist, the result is Typ[Invalid].</span>
<span id="L11" class="ln">    11&nbsp;&nbsp;</span><span class="comment">// under must only be called when a type is known</span>
<span id="L12" class="ln">    12&nbsp;&nbsp;</span><span class="comment">// to be fully set up.</span>
<span id="L13" class="ln">    13&nbsp;&nbsp;</span>func under(t Type) Type {
<span id="L14" class="ln">    14&nbsp;&nbsp;</span>	if t := asNamed(t); t != nil {
<span id="L15" class="ln">    15&nbsp;&nbsp;</span>		return t.under()
<span id="L16" class="ln">    16&nbsp;&nbsp;</span>	}
<span id="L17" class="ln">    17&nbsp;&nbsp;</span>	return t.Underlying()
<span id="L18" class="ln">    18&nbsp;&nbsp;</span>}
<span id="L19" class="ln">    19&nbsp;&nbsp;</span>
<span id="L20" class="ln">    20&nbsp;&nbsp;</span><span class="comment">// If t is not a type parameter, coreType returns the underlying type.</span>
<span id="L21" class="ln">    21&nbsp;&nbsp;</span><span class="comment">// If t is a type parameter, coreType returns the single underlying</span>
<span id="L22" class="ln">    22&nbsp;&nbsp;</span><span class="comment">// type of all types in its type set if it exists, or nil otherwise. If the</span>
<span id="L23" class="ln">    23&nbsp;&nbsp;</span><span class="comment">// type set contains only unrestricted and restricted channel types (with</span>
<span id="L24" class="ln">    24&nbsp;&nbsp;</span><span class="comment">// identical element types), the single underlying type is the restricted</span>
<span id="L25" class="ln">    25&nbsp;&nbsp;</span><span class="comment">// channel type if the restrictions are always the same, or nil otherwise.</span>
<span id="L26" class="ln">    26&nbsp;&nbsp;</span>func coreType(t Type) Type {
<span id="L27" class="ln">    27&nbsp;&nbsp;</span>	tpar, _ := t.(*TypeParam)
<span id="L28" class="ln">    28&nbsp;&nbsp;</span>	if tpar == nil {
<span id="L29" class="ln">    29&nbsp;&nbsp;</span>		return under(t)
<span id="L30" class="ln">    30&nbsp;&nbsp;</span>	}
<span id="L31" class="ln">    31&nbsp;&nbsp;</span>
<span id="L32" class="ln">    32&nbsp;&nbsp;</span>	var su Type
<span id="L33" class="ln">    33&nbsp;&nbsp;</span>	if tpar.underIs(func(u Type) bool {
<span id="L34" class="ln">    34&nbsp;&nbsp;</span>		if u == nil {
<span id="L35" class="ln">    35&nbsp;&nbsp;</span>			return false
<span id="L36" class="ln">    36&nbsp;&nbsp;</span>		}
<span id="L37" class="ln">    37&nbsp;&nbsp;</span>		if su != nil {
<span id="L38" class="ln">    38&nbsp;&nbsp;</span>			u = match(su, u)
<span id="L39" class="ln">    39&nbsp;&nbsp;</span>			if u == nil {
<span id="L40" class="ln">    40&nbsp;&nbsp;</span>				return false
<span id="L41" class="ln">    41&nbsp;&nbsp;</span>			}
<span id="L42" class="ln">    42&nbsp;&nbsp;</span>		}
<span id="L43" class="ln">    43&nbsp;&nbsp;</span>		<span class="comment">// su == nil || match(su, u) != nil</span>
<span id="L44" class="ln">    44&nbsp;&nbsp;</span>		su = u
<span id="L45" class="ln">    45&nbsp;&nbsp;</span>		return true
<span id="L46" class="ln">    46&nbsp;&nbsp;</span>	}) {
<span id="L47" class="ln">    47&nbsp;&nbsp;</span>		return su
<span id="L48" class="ln">    48&nbsp;&nbsp;</span>	}
<span id="L49" class="ln">    49&nbsp;&nbsp;</span>	return nil
<span id="L50" class="ln">    50&nbsp;&nbsp;</span>}
<span id="L51" class="ln">    51&nbsp;&nbsp;</span>
<span id="L52" class="ln">    52&nbsp;&nbsp;</span><span class="comment">// coreString is like coreType but also considers []byte</span>
<span id="L53" class="ln">    53&nbsp;&nbsp;</span><span class="comment">// and strings as identical. In this case, if successful and we saw</span>
<span id="L54" class="ln">    54&nbsp;&nbsp;</span><span class="comment">// a string, the result is of type (possibly untyped) string.</span>
<span id="L55" class="ln">    55&nbsp;&nbsp;</span>func coreString(t Type) Type {
<span id="L56" class="ln">    56&nbsp;&nbsp;</span>	tpar, _ := t.(*TypeParam)
<span id="L57" class="ln">    57&nbsp;&nbsp;</span>	if tpar == nil {
<span id="L58" class="ln">    58&nbsp;&nbsp;</span>		return under(t) <span class="comment">// string or untyped string</span>
<span id="L59" class="ln">    59&nbsp;&nbsp;</span>	}
<span id="L60" class="ln">    60&nbsp;&nbsp;</span>
<span id="L61" class="ln">    61&nbsp;&nbsp;</span>	var su Type
<span id="L62" class="ln">    62&nbsp;&nbsp;</span>	hasString := false
<span id="L63" class="ln">    63&nbsp;&nbsp;</span>	if tpar.underIs(func(u Type) bool {
<span id="L64" class="ln">    64&nbsp;&nbsp;</span>		if u == nil {
<span id="L65" class="ln">    65&nbsp;&nbsp;</span>			return false
<span id="L66" class="ln">    66&nbsp;&nbsp;</span>		}
<span id="L67" class="ln">    67&nbsp;&nbsp;</span>		if isString(u) {
<span id="L68" class="ln">    68&nbsp;&nbsp;</span>			u = NewSlice(universeByte)
<span id="L69" class="ln">    69&nbsp;&nbsp;</span>			hasString = true
<span id="L70" class="ln">    70&nbsp;&nbsp;</span>		}
<span id="L71" class="ln">    71&nbsp;&nbsp;</span>		if su != nil {
<span id="L72" class="ln">    72&nbsp;&nbsp;</span>			u = match(su, u)
<span id="L73" class="ln">    73&nbsp;&nbsp;</span>			if u == nil {
<span id="L74" class="ln">    74&nbsp;&nbsp;</span>				return false
<span id="L75" class="ln">    75&nbsp;&nbsp;</span>			}
<span id="L76" class="ln">    76&nbsp;&nbsp;</span>		}
<span id="L77" class="ln">    77&nbsp;&nbsp;</span>		<span class="comment">// su == nil || match(su, u) != nil</span>
<span id="L78" class="ln">    78&nbsp;&nbsp;</span>		su = u
<span id="L79" class="ln">    79&nbsp;&nbsp;</span>		return true
<span id="L80" class="ln">    80&nbsp;&nbsp;</span>	}) {
<span id="L81" class="ln">    81&nbsp;&nbsp;</span>		if hasString {
<span id="L82" class="ln">    82&nbsp;&nbsp;</span>			return Typ[String]
<span id="L83" class="ln">    83&nbsp;&nbsp;</span>		}
<span id="L84" class="ln">    84&nbsp;&nbsp;</span>		return su
<span id="L85" class="ln">    85&nbsp;&nbsp;</span>	}
<span id="L86" class="ln">    86&nbsp;&nbsp;</span>	return nil
<span id="L87" class="ln">    87&nbsp;&nbsp;</span>}
<span id="L88" class="ln">    88&nbsp;&nbsp;</span>
<span id="L89" class="ln">    89&nbsp;&nbsp;</span><span class="comment">// If x and y are identical, match returns x.</span>
<span id="L90" class="ln">    90&nbsp;&nbsp;</span><span class="comment">// If x and y are identical channels but for their direction</span>
<span id="L91" class="ln">    91&nbsp;&nbsp;</span><span class="comment">// and one of them is unrestricted, match returns the channel</span>
<span id="L92" class="ln">    92&nbsp;&nbsp;</span><span class="comment">// with the restricted direction.</span>
<span id="L93" class="ln">    93&nbsp;&nbsp;</span><span class="comment">// In all other cases, match returns nil.</span>
<span id="L94" class="ln">    94&nbsp;&nbsp;</span>func match(x, y Type) Type {
<span id="L95" class="ln">    95&nbsp;&nbsp;</span>	<span class="comment">// Common case: we don&#39;t have channels.</span>
<span id="L96" class="ln">    96&nbsp;&nbsp;</span>	if Identical(x, y) {
<span id="L97" class="ln">    97&nbsp;&nbsp;</span>		return x
<span id="L98" class="ln">    98&nbsp;&nbsp;</span>	}
<span id="L99" class="ln">    99&nbsp;&nbsp;</span>
<span id="L100" class="ln">   100&nbsp;&nbsp;</span>	<span class="comment">// We may have channels that differ in direction only.</span>
<span id="L101" class="ln">   101&nbsp;&nbsp;</span>	if x, _ := x.(*Chan); x != nil {
<span id="L102" class="ln">   102&nbsp;&nbsp;</span>		if y, _ := y.(*Chan); y != nil &amp;&amp; Identical(x.elem, y.elem) {
<span id="L103" class="ln">   103&nbsp;&nbsp;</span>			<span class="comment">// We have channels that differ in direction only.</span>
<span id="L104" class="ln">   104&nbsp;&nbsp;</span>			<span class="comment">// If there&#39;s an unrestricted channel, select the restricted one.</span>
<span id="L105" class="ln">   105&nbsp;&nbsp;</span>			switch {
<span id="L106" class="ln">   106&nbsp;&nbsp;</span>			case x.dir == SendRecv:
<span id="L107" class="ln">   107&nbsp;&nbsp;</span>				return y
<span id="L108" class="ln">   108&nbsp;&nbsp;</span>			case y.dir == SendRecv:
<span id="L109" class="ln">   109&nbsp;&nbsp;</span>				return x
<span id="L110" class="ln">   110&nbsp;&nbsp;</span>			}
<span id="L111" class="ln">   111&nbsp;&nbsp;</span>		}
<span id="L112" class="ln">   112&nbsp;&nbsp;</span>	}
<span id="L113" class="ln">   113&nbsp;&nbsp;</span>
<span id="L114" class="ln">   114&nbsp;&nbsp;</span>	<span class="comment">// types are different</span>
<span id="L115" class="ln">   115&nbsp;&nbsp;</span>	return nil
<span id="L116" class="ln">   116&nbsp;&nbsp;</span>}
<span id="L117" class="ln">   117&nbsp;&nbsp;</span>
</pre><p><a href="under.go?m=text">View as plain text</a></p>

<div id="footer">
Build version go1.22.2.<br>
Except as <a href="https://developers.google.com/site-policies#restrictions">noted</a>,
the content of this page is licensed under the
Creative Commons Attribution 3.0 License,
and code is licensed under a <a href="http://localhost:8080/LICENSE">BSD license</a>.<br>
<a href="https://golang.org/doc/tos.html">Terms of Service</a> |
<a href="https://www.google.com/intl/en/policies/privacy/">Privacy Policy</a>
</div>

</div><!-- .container -->
</div><!-- #page -->
</body>
</html>
