<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#375EAB">

  <title>src/regexp/syntax/perl_groups.go - Go Documentation Server</title>

<link type="text/css" rel="stylesheet" href="../../../lib/godoc/style.css">

<script>window.initFuncs = [];</script>
<script src="../../../lib/godoc/jquery.js" defer></script>



<script>var goVersion = "go1.22.2";</script>
<script src="../../../lib/godoc/godocs.js" defer></script>
</head>
<body>

<div id='lowframe' style="position: fixed; bottom: 0; left: 0; height: 0; width: 100%; border-top: thin solid grey; background-color: white; overflow: auto;">
...
</div><!-- #lowframe -->

<div id="topbar" class="wide"><div class="container">
<div class="top-heading" id="heading-wide"><a href="../../../index.html">Go Documentation Server</a></div>
<div class="top-heading" id="heading-narrow"><a href="../../../index.html">GoDoc</a></div>
<a href="perl_groups.go#" id="menu-button"><span id="menu-button-arrow">&#9661;</span></a>
<form method="GET" action="http://localhost:8080/search">
<div id="menu">

<span class="search-box"><input type="search" id="search" name="q" placeholder="Search" aria-label="Search" required><button type="submit"><span><!-- magnifying glass: --><svg width="24" height="24" viewBox="0 0 24 24"><title>submit search</title><path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/><path d="M0 0h24v24H0z" fill="none"/></svg></span></button></span>
</div>
</form>

</div></div>



<div id="page" class="wide">
<div class="container">


  <h1>
    Source file
    <a href="http://localhost:8080/src">src</a>/<a href="http://localhost:8080/src/regexp">regexp</a>/<a href="http://localhost:8080/src/regexp/syntax">syntax</a>/<span class="text-muted">perl_groups.go</span>
  </h1>





  <h2>
    Documentation: <a href="http://localhost:8080/pkg/regexp/syntax">regexp/syntax</a>
  </h2>



<div id="nav"></div>


<script type='text/javascript'>document.ANALYSIS_DATA = null;</script>
<pre><span id="L1" class="ln">     1&nbsp;&nbsp;</span><span class="comment">// Copyright 2013 The Go Authors. All rights reserved.</span>
<span id="L2" class="ln">     2&nbsp;&nbsp;</span><span class="comment">// Use of this source code is governed by a BSD-style</span>
<span id="L3" class="ln">     3&nbsp;&nbsp;</span><span class="comment">// license that can be found in the LICENSE file.</span>
<span id="L4" class="ln">     4&nbsp;&nbsp;</span>
<span id="L5" class="ln">     5&nbsp;&nbsp;</span><span class="comment">// GENERATED BY make_perl_groups.pl; DO NOT EDIT.</span>
<span id="L6" class="ln">     6&nbsp;&nbsp;</span><span class="comment">// make_perl_groups.pl &gt;perl_groups.go</span>
<span id="L7" class="ln">     7&nbsp;&nbsp;</span>
<span id="L8" class="ln">     8&nbsp;&nbsp;</span>package syntax
<span id="L9" class="ln">     9&nbsp;&nbsp;</span>
<span id="L10" class="ln">    10&nbsp;&nbsp;</span>var code1 = []rune{ <span class="comment">/* \d */</span>
<span id="L11" class="ln">    11&nbsp;&nbsp;</span>	0x30, 0x39,
<span id="L12" class="ln">    12&nbsp;&nbsp;</span>}
<span id="L13" class="ln">    13&nbsp;&nbsp;</span>
<span id="L14" class="ln">    14&nbsp;&nbsp;</span>var code2 = []rune{ <span class="comment">/* \s */</span>
<span id="L15" class="ln">    15&nbsp;&nbsp;</span>	0x9, 0xa,
<span id="L16" class="ln">    16&nbsp;&nbsp;</span>	0xc, 0xd,
<span id="L17" class="ln">    17&nbsp;&nbsp;</span>	0x20, 0x20,
<span id="L18" class="ln">    18&nbsp;&nbsp;</span>}
<span id="L19" class="ln">    19&nbsp;&nbsp;</span>
<span id="L20" class="ln">    20&nbsp;&nbsp;</span>var code3 = []rune{ <span class="comment">/* \w */</span>
<span id="L21" class="ln">    21&nbsp;&nbsp;</span>	0x30, 0x39,
<span id="L22" class="ln">    22&nbsp;&nbsp;</span>	0x41, 0x5a,
<span id="L23" class="ln">    23&nbsp;&nbsp;</span>	0x5f, 0x5f,
<span id="L24" class="ln">    24&nbsp;&nbsp;</span>	0x61, 0x7a,
<span id="L25" class="ln">    25&nbsp;&nbsp;</span>}
<span id="L26" class="ln">    26&nbsp;&nbsp;</span>
<span id="L27" class="ln">    27&nbsp;&nbsp;</span>var perlGroup = map[string]charGroup{
<span id="L28" class="ln">    28&nbsp;&nbsp;</span>	`\d`: {+1, code1},
<span id="L29" class="ln">    29&nbsp;&nbsp;</span>	`\D`: {-1, code1},
<span id="L30" class="ln">    30&nbsp;&nbsp;</span>	`\s`: {+1, code2},
<span id="L31" class="ln">    31&nbsp;&nbsp;</span>	`\S`: {-1, code2},
<span id="L32" class="ln">    32&nbsp;&nbsp;</span>	`\w`: {+1, code3},
<span id="L33" class="ln">    33&nbsp;&nbsp;</span>	`\W`: {-1, code3},
<span id="L34" class="ln">    34&nbsp;&nbsp;</span>}
<span id="L35" class="ln">    35&nbsp;&nbsp;</span>var code4 = []rune{ <span class="comment">/* [:alnum:] */</span>
<span id="L36" class="ln">    36&nbsp;&nbsp;</span>	0x30, 0x39,
<span id="L37" class="ln">    37&nbsp;&nbsp;</span>	0x41, 0x5a,
<span id="L38" class="ln">    38&nbsp;&nbsp;</span>	0x61, 0x7a,
<span id="L39" class="ln">    39&nbsp;&nbsp;</span>}
<span id="L40" class="ln">    40&nbsp;&nbsp;</span>
<span id="L41" class="ln">    41&nbsp;&nbsp;</span>var code5 = []rune{ <span class="comment">/* [:alpha:] */</span>
<span id="L42" class="ln">    42&nbsp;&nbsp;</span>	0x41, 0x5a,
<span id="L43" class="ln">    43&nbsp;&nbsp;</span>	0x61, 0x7a,
<span id="L44" class="ln">    44&nbsp;&nbsp;</span>}
<span id="L45" class="ln">    45&nbsp;&nbsp;</span>
<span id="L46" class="ln">    46&nbsp;&nbsp;</span>var code6 = []rune{ <span class="comment">/* [:ascii:] */</span>
<span id="L47" class="ln">    47&nbsp;&nbsp;</span>	0x0, 0x7f,
<span id="L48" class="ln">    48&nbsp;&nbsp;</span>}
<span id="L49" class="ln">    49&nbsp;&nbsp;</span>
<span id="L50" class="ln">    50&nbsp;&nbsp;</span>var code7 = []rune{ <span class="comment">/* [:blank:] */</span>
<span id="L51" class="ln">    51&nbsp;&nbsp;</span>	0x9, 0x9,
<span id="L52" class="ln">    52&nbsp;&nbsp;</span>	0x20, 0x20,
<span id="L53" class="ln">    53&nbsp;&nbsp;</span>}
<span id="L54" class="ln">    54&nbsp;&nbsp;</span>
<span id="L55" class="ln">    55&nbsp;&nbsp;</span>var code8 = []rune{ <span class="comment">/* [:cntrl:] */</span>
<span id="L56" class="ln">    56&nbsp;&nbsp;</span>	0x0, 0x1f,
<span id="L57" class="ln">    57&nbsp;&nbsp;</span>	0x7f, 0x7f,
<span id="L58" class="ln">    58&nbsp;&nbsp;</span>}
<span id="L59" class="ln">    59&nbsp;&nbsp;</span>
<span id="L60" class="ln">    60&nbsp;&nbsp;</span>var code9 = []rune{ <span class="comment">/* [:digit:] */</span>
<span id="L61" class="ln">    61&nbsp;&nbsp;</span>	0x30, 0x39,
<span id="L62" class="ln">    62&nbsp;&nbsp;</span>}
<span id="L63" class="ln">    63&nbsp;&nbsp;</span>
<span id="L64" class="ln">    64&nbsp;&nbsp;</span>var code10 = []rune{ <span class="comment">/* [:graph:] */</span>
<span id="L65" class="ln">    65&nbsp;&nbsp;</span>	0x21, 0x7e,
<span id="L66" class="ln">    66&nbsp;&nbsp;</span>}
<span id="L67" class="ln">    67&nbsp;&nbsp;</span>
<span id="L68" class="ln">    68&nbsp;&nbsp;</span>var code11 = []rune{ <span class="comment">/* [:lower:] */</span>
<span id="L69" class="ln">    69&nbsp;&nbsp;</span>	0x61, 0x7a,
<span id="L70" class="ln">    70&nbsp;&nbsp;</span>}
<span id="L71" class="ln">    71&nbsp;&nbsp;</span>
<span id="L72" class="ln">    72&nbsp;&nbsp;</span>var code12 = []rune{ <span class="comment">/* [:print:] */</span>
<span id="L73" class="ln">    73&nbsp;&nbsp;</span>	0x20, 0x7e,
<span id="L74" class="ln">    74&nbsp;&nbsp;</span>}
<span id="L75" class="ln">    75&nbsp;&nbsp;</span>
<span id="L76" class="ln">    76&nbsp;&nbsp;</span>var code13 = []rune{ <span class="comment">/* [:punct:] */</span>
<span id="L77" class="ln">    77&nbsp;&nbsp;</span>	0x21, 0x2f,
<span id="L78" class="ln">    78&nbsp;&nbsp;</span>	0x3a, 0x40,
<span id="L79" class="ln">    79&nbsp;&nbsp;</span>	0x5b, 0x60,
<span id="L80" class="ln">    80&nbsp;&nbsp;</span>	0x7b, 0x7e,
<span id="L81" class="ln">    81&nbsp;&nbsp;</span>}
<span id="L82" class="ln">    82&nbsp;&nbsp;</span>
<span id="L83" class="ln">    83&nbsp;&nbsp;</span>var code14 = []rune{ <span class="comment">/* [:space:] */</span>
<span id="L84" class="ln">    84&nbsp;&nbsp;</span>	0x9, 0xd,
<span id="L85" class="ln">    85&nbsp;&nbsp;</span>	0x20, 0x20,
<span id="L86" class="ln">    86&nbsp;&nbsp;</span>}
<span id="L87" class="ln">    87&nbsp;&nbsp;</span>
<span id="L88" class="ln">    88&nbsp;&nbsp;</span>var code15 = []rune{ <span class="comment">/* [:upper:] */</span>
<span id="L89" class="ln">    89&nbsp;&nbsp;</span>	0x41, 0x5a,
<span id="L90" class="ln">    90&nbsp;&nbsp;</span>}
<span id="L91" class="ln">    91&nbsp;&nbsp;</span>
<span id="L92" class="ln">    92&nbsp;&nbsp;</span>var code16 = []rune{ <span class="comment">/* [:word:] */</span>
<span id="L93" class="ln">    93&nbsp;&nbsp;</span>	0x30, 0x39,
<span id="L94" class="ln">    94&nbsp;&nbsp;</span>	0x41, 0x5a,
<span id="L95" class="ln">    95&nbsp;&nbsp;</span>	0x5f, 0x5f,
<span id="L96" class="ln">    96&nbsp;&nbsp;</span>	0x61, 0x7a,
<span id="L97" class="ln">    97&nbsp;&nbsp;</span>}
<span id="L98" class="ln">    98&nbsp;&nbsp;</span>
<span id="L99" class="ln">    99&nbsp;&nbsp;</span>var code17 = []rune{ <span class="comment">/* [:xdigit:] */</span>
<span id="L100" class="ln">   100&nbsp;&nbsp;</span>	0x30, 0x39,
<span id="L101" class="ln">   101&nbsp;&nbsp;</span>	0x41, 0x46,
<span id="L102" class="ln">   102&nbsp;&nbsp;</span>	0x61, 0x66,
<span id="L103" class="ln">   103&nbsp;&nbsp;</span>}
<span id="L104" class="ln">   104&nbsp;&nbsp;</span>
<span id="L105" class="ln">   105&nbsp;&nbsp;</span>var posixGroup = map[string]charGroup{
<span id="L106" class="ln">   106&nbsp;&nbsp;</span>	`[:alnum:]`:   {+1, code4},
<span id="L107" class="ln">   107&nbsp;&nbsp;</span>	`[:^alnum:]`:  {-1, code4},
<span id="L108" class="ln">   108&nbsp;&nbsp;</span>	`[:alpha:]`:   {+1, code5},
<span id="L109" class="ln">   109&nbsp;&nbsp;</span>	`[:^alpha:]`:  {-1, code5},
<span id="L110" class="ln">   110&nbsp;&nbsp;</span>	`[:ascii:]`:   {+1, code6},
<span id="L111" class="ln">   111&nbsp;&nbsp;</span>	`[:^ascii:]`:  {-1, code6},
<span id="L112" class="ln">   112&nbsp;&nbsp;</span>	`[:blank:]`:   {+1, code7},
<span id="L113" class="ln">   113&nbsp;&nbsp;</span>	`[:^blank:]`:  {-1, code7},
<span id="L114" class="ln">   114&nbsp;&nbsp;</span>	`[:cntrl:]`:   {+1, code8},
<span id="L115" class="ln">   115&nbsp;&nbsp;</span>	`[:^cntrl:]`:  {-1, code8},
<span id="L116" class="ln">   116&nbsp;&nbsp;</span>	`[:digit:]`:   {+1, code9},
<span id="L117" class="ln">   117&nbsp;&nbsp;</span>	`[:^digit:]`:  {-1, code9},
<span id="L118" class="ln">   118&nbsp;&nbsp;</span>	`[:graph:]`:   {+1, code10},
<span id="L119" class="ln">   119&nbsp;&nbsp;</span>	`[:^graph:]`:  {-1, code10},
<span id="L120" class="ln">   120&nbsp;&nbsp;</span>	`[:lower:]`:   {+1, code11},
<span id="L121" class="ln">   121&nbsp;&nbsp;</span>	`[:^lower:]`:  {-1, code11},
<span id="L122" class="ln">   122&nbsp;&nbsp;</span>	`[:print:]`:   {+1, code12},
<span id="L123" class="ln">   123&nbsp;&nbsp;</span>	`[:^print:]`:  {-1, code12},
<span id="L124" class="ln">   124&nbsp;&nbsp;</span>	`[:punct:]`:   {+1, code13},
<span id="L125" class="ln">   125&nbsp;&nbsp;</span>	`[:^punct:]`:  {-1, code13},
<span id="L126" class="ln">   126&nbsp;&nbsp;</span>	`[:space:]`:   {+1, code14},
<span id="L127" class="ln">   127&nbsp;&nbsp;</span>	`[:^space:]`:  {-1, code14},
<span id="L128" class="ln">   128&nbsp;&nbsp;</span>	`[:upper:]`:   {+1, code15},
<span id="L129" class="ln">   129&nbsp;&nbsp;</span>	`[:^upper:]`:  {-1, code15},
<span id="L130" class="ln">   130&nbsp;&nbsp;</span>	`[:word:]`:    {+1, code16},
<span id="L131" class="ln">   131&nbsp;&nbsp;</span>	`[:^word:]`:   {-1, code16},
<span id="L132" class="ln">   132&nbsp;&nbsp;</span>	`[:xdigit:]`:  {+1, code17},
<span id="L133" class="ln">   133&nbsp;&nbsp;</span>	`[:^xdigit:]`: {-1, code17},
<span id="L134" class="ln">   134&nbsp;&nbsp;</span>}
<span id="L135" class="ln">   135&nbsp;&nbsp;</span>
</pre><p><a href="perl_groups.go?m=text">View as plain text</a></p>

<div id="footer">
Build version go1.22.2.<br>
Except as <a href="https://developers.google.com/site-policies#restrictions">noted</a>,
the content of this page is licensed under the
Creative Commons Attribution 3.0 License,
and code is licensed under a <a href="http://localhost:8080/LICENSE">BSD license</a>.<br>
<a href="https://golang.org/doc/tos.html">Terms of Service</a> |
<a href="https://www.google.com/intl/en/policies/privacy/">Privacy Policy</a>
</div>

</div><!-- .container -->
</div><!-- #page -->
</body>
</html>
