<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#375EAB">

  <title>src/syscall/zsysnum_linux_amd64.go - Go Documentation Server</title>

<link type="text/css" rel="stylesheet" href="../../lib/godoc/style.css">

<script>window.initFuncs = [];</script>
<script src="../../lib/godoc/jquery.js" defer></script>



<script>var goVersion = "go1.22.2";</script>
<script src="../../lib/godoc/godocs.js" defer></script>
</head>
<body>

<div id='lowframe' style="position: fixed; bottom: 0; left: 0; height: 0; width: 100%; border-top: thin solid grey; background-color: white; overflow: auto;">
...
</div><!-- #lowframe -->

<div id="topbar" class="wide"><div class="container">
<div class="top-heading" id="heading-wide"><a href="../../index.html">Go Documentation Server</a></div>
<div class="top-heading" id="heading-narrow"><a href="../../index.html">GoDoc</a></div>
<a href="zsysnum_linux_amd64.go#" id="menu-button"><span id="menu-button-arrow">&#9661;</span></a>
<form method="GET" action="http://localhost:8080/search">
<div id="menu">

<span class="search-box"><input type="search" id="search" name="q" placeholder="Search" aria-label="Search" required><button type="submit"><span><!-- magnifying glass: --><svg width="24" height="24" viewBox="0 0 24 24"><title>submit search</title><path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/><path d="M0 0h24v24H0z" fill="none"/></svg></span></button></span>
</div>
</form>

</div></div>



<div id="page" class="wide">
<div class="container">


  <h1>
    Source file
    <a href="http://localhost:8080/src">src</a>/<a href="http://localhost:8080/src/syscall">syscall</a>/<span class="text-muted">zsysnum_linux_amd64.go</span>
  </h1>





  <h2>
    Documentation: <a href="http://localhost:8080/pkg/syscall">syscall</a>
  </h2>



<div id="nav"></div>


<script type='text/javascript'>document.ANALYSIS_DATA = null;</script>
<pre><span id="L1" class="ln">     1&nbsp;&nbsp;</span><span class="comment">// mksysnum_linux.pl /usr/include/asm/unistd_64.h</span>
<span id="L2" class="ln">     2&nbsp;&nbsp;</span><span class="comment">// Code generated by the command above; DO NOT EDIT.</span>
<span id="L3" class="ln">     3&nbsp;&nbsp;</span>
<span id="L4" class="ln">     4&nbsp;&nbsp;</span><span class="comment">//go:build amd64 &amp;&amp; linux</span>
<span id="L5" class="ln">     5&nbsp;&nbsp;</span>
<span id="L6" class="ln">     6&nbsp;&nbsp;</span>package syscall
<span id="L7" class="ln">     7&nbsp;&nbsp;</span>
<span id="L8" class="ln">     8&nbsp;&nbsp;</span>const (
<span id="L9" class="ln">     9&nbsp;&nbsp;</span>	SYS_READ                   = 0
<span id="L10" class="ln">    10&nbsp;&nbsp;</span>	SYS_WRITE                  = 1
<span id="L11" class="ln">    11&nbsp;&nbsp;</span>	SYS_OPEN                   = 2
<span id="L12" class="ln">    12&nbsp;&nbsp;</span>	SYS_CLOSE                  = 3
<span id="L13" class="ln">    13&nbsp;&nbsp;</span>	SYS_STAT                   = 4
<span id="L14" class="ln">    14&nbsp;&nbsp;</span>	SYS_FSTAT                  = 5
<span id="L15" class="ln">    15&nbsp;&nbsp;</span>	SYS_LSTAT                  = 6
<span id="L16" class="ln">    16&nbsp;&nbsp;</span>	SYS_POLL                   = 7
<span id="L17" class="ln">    17&nbsp;&nbsp;</span>	SYS_LSEEK                  = 8
<span id="L18" class="ln">    18&nbsp;&nbsp;</span>	SYS_MMAP                   = 9
<span id="L19" class="ln">    19&nbsp;&nbsp;</span>	SYS_MPROTECT               = 10
<span id="L20" class="ln">    20&nbsp;&nbsp;</span>	SYS_MUNMAP                 = 11
<span id="L21" class="ln">    21&nbsp;&nbsp;</span>	SYS_BRK                    = 12
<span id="L22" class="ln">    22&nbsp;&nbsp;</span>	SYS_RT_SIGACTION           = 13
<span id="L23" class="ln">    23&nbsp;&nbsp;</span>	SYS_RT_SIGPROCMASK         = 14
<span id="L24" class="ln">    24&nbsp;&nbsp;</span>	SYS_RT_SIGRETURN           = 15
<span id="L25" class="ln">    25&nbsp;&nbsp;</span>	SYS_IOCTL                  = 16
<span id="L26" class="ln">    26&nbsp;&nbsp;</span>	SYS_PREAD64                = 17
<span id="L27" class="ln">    27&nbsp;&nbsp;</span>	SYS_PWRITE64               = 18
<span id="L28" class="ln">    28&nbsp;&nbsp;</span>	SYS_READV                  = 19
<span id="L29" class="ln">    29&nbsp;&nbsp;</span>	SYS_WRITEV                 = 20
<span id="L30" class="ln">    30&nbsp;&nbsp;</span>	SYS_ACCESS                 = 21
<span id="L31" class="ln">    31&nbsp;&nbsp;</span>	SYS_PIPE                   = 22
<span id="L32" class="ln">    32&nbsp;&nbsp;</span>	SYS_SELECT                 = 23
<span id="L33" class="ln">    33&nbsp;&nbsp;</span>	SYS_SCHED_YIELD            = 24
<span id="L34" class="ln">    34&nbsp;&nbsp;</span>	SYS_MREMAP                 = 25
<span id="L35" class="ln">    35&nbsp;&nbsp;</span>	SYS_MSYNC                  = 26
<span id="L36" class="ln">    36&nbsp;&nbsp;</span>	SYS_MINCORE                = 27
<span id="L37" class="ln">    37&nbsp;&nbsp;</span>	SYS_MADVISE                = 28
<span id="L38" class="ln">    38&nbsp;&nbsp;</span>	SYS_SHMGET                 = 29
<span id="L39" class="ln">    39&nbsp;&nbsp;</span>	SYS_SHMAT                  = 30
<span id="L40" class="ln">    40&nbsp;&nbsp;</span>	SYS_SHMCTL                 = 31
<span id="L41" class="ln">    41&nbsp;&nbsp;</span>	SYS_DUP                    = 32
<span id="L42" class="ln">    42&nbsp;&nbsp;</span>	SYS_DUP2                   = 33
<span id="L43" class="ln">    43&nbsp;&nbsp;</span>	SYS_PAUSE                  = 34
<span id="L44" class="ln">    44&nbsp;&nbsp;</span>	SYS_NANOSLEEP              = 35
<span id="L45" class="ln">    45&nbsp;&nbsp;</span>	SYS_GETITIMER              = 36
<span id="L46" class="ln">    46&nbsp;&nbsp;</span>	SYS_ALARM                  = 37
<span id="L47" class="ln">    47&nbsp;&nbsp;</span>	SYS_SETITIMER              = 38
<span id="L48" class="ln">    48&nbsp;&nbsp;</span>	SYS_GETPID                 = 39
<span id="L49" class="ln">    49&nbsp;&nbsp;</span>	SYS_SENDFILE               = 40
<span id="L50" class="ln">    50&nbsp;&nbsp;</span>	SYS_SOCKET                 = 41
<span id="L51" class="ln">    51&nbsp;&nbsp;</span>	SYS_CONNECT                = 42
<span id="L52" class="ln">    52&nbsp;&nbsp;</span>	SYS_ACCEPT                 = 43
<span id="L53" class="ln">    53&nbsp;&nbsp;</span>	SYS_SENDTO                 = 44
<span id="L54" class="ln">    54&nbsp;&nbsp;</span>	SYS_RECVFROM               = 45
<span id="L55" class="ln">    55&nbsp;&nbsp;</span>	SYS_SENDMSG                = 46
<span id="L56" class="ln">    56&nbsp;&nbsp;</span>	SYS_RECVMSG                = 47
<span id="L57" class="ln">    57&nbsp;&nbsp;</span>	SYS_SHUTDOWN               = 48
<span id="L58" class="ln">    58&nbsp;&nbsp;</span>	SYS_BIND                   = 49
<span id="L59" class="ln">    59&nbsp;&nbsp;</span>	SYS_LISTEN                 = 50
<span id="L60" class="ln">    60&nbsp;&nbsp;</span>	SYS_GETSOCKNAME            = 51
<span id="L61" class="ln">    61&nbsp;&nbsp;</span>	SYS_GETPEERNAME            = 52
<span id="L62" class="ln">    62&nbsp;&nbsp;</span>	SYS_SOCKETPAIR             = 53
<span id="L63" class="ln">    63&nbsp;&nbsp;</span>	SYS_SETSOCKOPT             = 54
<span id="L64" class="ln">    64&nbsp;&nbsp;</span>	SYS_GETSOCKOPT             = 55
<span id="L65" class="ln">    65&nbsp;&nbsp;</span>	SYS_CLONE                  = 56
<span id="L66" class="ln">    66&nbsp;&nbsp;</span>	SYS_FORK                   = 57
<span id="L67" class="ln">    67&nbsp;&nbsp;</span>	SYS_VFORK                  = 58
<span id="L68" class="ln">    68&nbsp;&nbsp;</span>	SYS_EXECVE                 = 59
<span id="L69" class="ln">    69&nbsp;&nbsp;</span>	SYS_EXIT                   = 60
<span id="L70" class="ln">    70&nbsp;&nbsp;</span>	SYS_WAIT4                  = 61
<span id="L71" class="ln">    71&nbsp;&nbsp;</span>	SYS_KILL                   = 62
<span id="L72" class="ln">    72&nbsp;&nbsp;</span>	SYS_UNAME                  = 63
<span id="L73" class="ln">    73&nbsp;&nbsp;</span>	SYS_SEMGET                 = 64
<span id="L74" class="ln">    74&nbsp;&nbsp;</span>	SYS_SEMOP                  = 65
<span id="L75" class="ln">    75&nbsp;&nbsp;</span>	SYS_SEMCTL                 = 66
<span id="L76" class="ln">    76&nbsp;&nbsp;</span>	SYS_SHMDT                  = 67
<span id="L77" class="ln">    77&nbsp;&nbsp;</span>	SYS_MSGGET                 = 68
<span id="L78" class="ln">    78&nbsp;&nbsp;</span>	SYS_MSGSND                 = 69
<span id="L79" class="ln">    79&nbsp;&nbsp;</span>	SYS_MSGRCV                 = 70
<span id="L80" class="ln">    80&nbsp;&nbsp;</span>	SYS_MSGCTL                 = 71
<span id="L81" class="ln">    81&nbsp;&nbsp;</span>	SYS_FCNTL                  = 72
<span id="L82" class="ln">    82&nbsp;&nbsp;</span>	SYS_FLOCK                  = 73
<span id="L83" class="ln">    83&nbsp;&nbsp;</span>	SYS_FSYNC                  = 74
<span id="L84" class="ln">    84&nbsp;&nbsp;</span>	SYS_FDATASYNC              = 75
<span id="L85" class="ln">    85&nbsp;&nbsp;</span>	SYS_TRUNCATE               = 76
<span id="L86" class="ln">    86&nbsp;&nbsp;</span>	SYS_FTRUNCATE              = 77
<span id="L87" class="ln">    87&nbsp;&nbsp;</span>	SYS_GETDENTS               = 78
<span id="L88" class="ln">    88&nbsp;&nbsp;</span>	SYS_GETCWD                 = 79
<span id="L89" class="ln">    89&nbsp;&nbsp;</span>	SYS_CHDIR                  = 80
<span id="L90" class="ln">    90&nbsp;&nbsp;</span>	SYS_FCHDIR                 = 81
<span id="L91" class="ln">    91&nbsp;&nbsp;</span>	SYS_RENAME                 = 82
<span id="L92" class="ln">    92&nbsp;&nbsp;</span>	SYS_MKDIR                  = 83
<span id="L93" class="ln">    93&nbsp;&nbsp;</span>	SYS_RMDIR                  = 84
<span id="L94" class="ln">    94&nbsp;&nbsp;</span>	SYS_CREAT                  = 85
<span id="L95" class="ln">    95&nbsp;&nbsp;</span>	SYS_LINK                   = 86
<span id="L96" class="ln">    96&nbsp;&nbsp;</span>	SYS_UNLINK                 = 87
<span id="L97" class="ln">    97&nbsp;&nbsp;</span>	SYS_SYMLINK                = 88
<span id="L98" class="ln">    98&nbsp;&nbsp;</span>	SYS_READLINK               = 89
<span id="L99" class="ln">    99&nbsp;&nbsp;</span>	SYS_CHMOD                  = 90
<span id="L100" class="ln">   100&nbsp;&nbsp;</span>	SYS_FCHMOD                 = 91
<span id="L101" class="ln">   101&nbsp;&nbsp;</span>	SYS_CHOWN                  = 92
<span id="L102" class="ln">   102&nbsp;&nbsp;</span>	SYS_FCHOWN                 = 93
<span id="L103" class="ln">   103&nbsp;&nbsp;</span>	SYS_LCHOWN                 = 94
<span id="L104" class="ln">   104&nbsp;&nbsp;</span>	SYS_UMASK                  = 95
<span id="L105" class="ln">   105&nbsp;&nbsp;</span>	SYS_GETTIMEOFDAY           = 96
<span id="L106" class="ln">   106&nbsp;&nbsp;</span>	SYS_GETRLIMIT              = 97
<span id="L107" class="ln">   107&nbsp;&nbsp;</span>	SYS_GETRUSAGE              = 98
<span id="L108" class="ln">   108&nbsp;&nbsp;</span>	SYS_SYSINFO                = 99
<span id="L109" class="ln">   109&nbsp;&nbsp;</span>	SYS_TIMES                  = 100
<span id="L110" class="ln">   110&nbsp;&nbsp;</span>	SYS_PTRACE                 = 101
<span id="L111" class="ln">   111&nbsp;&nbsp;</span>	SYS_GETUID                 = 102
<span id="L112" class="ln">   112&nbsp;&nbsp;</span>	SYS_SYSLOG                 = 103
<span id="L113" class="ln">   113&nbsp;&nbsp;</span>	SYS_GETGID                 = 104
<span id="L114" class="ln">   114&nbsp;&nbsp;</span>	SYS_SETUID                 = 105
<span id="L115" class="ln">   115&nbsp;&nbsp;</span>	SYS_SETGID                 = 106
<span id="L116" class="ln">   116&nbsp;&nbsp;</span>	SYS_GETEUID                = 107
<span id="L117" class="ln">   117&nbsp;&nbsp;</span>	SYS_GETEGID                = 108
<span id="L118" class="ln">   118&nbsp;&nbsp;</span>	SYS_SETPGID                = 109
<span id="L119" class="ln">   119&nbsp;&nbsp;</span>	SYS_GETPPID                = 110
<span id="L120" class="ln">   120&nbsp;&nbsp;</span>	SYS_GETPGRP                = 111
<span id="L121" class="ln">   121&nbsp;&nbsp;</span>	SYS_SETSID                 = 112
<span id="L122" class="ln">   122&nbsp;&nbsp;</span>	SYS_SETREUID               = 113
<span id="L123" class="ln">   123&nbsp;&nbsp;</span>	SYS_SETREGID               = 114
<span id="L124" class="ln">   124&nbsp;&nbsp;</span>	SYS_GETGROUPS              = 115
<span id="L125" class="ln">   125&nbsp;&nbsp;</span>	SYS_SETGROUPS              = 116
<span id="L126" class="ln">   126&nbsp;&nbsp;</span>	SYS_SETRESUID              = 117
<span id="L127" class="ln">   127&nbsp;&nbsp;</span>	SYS_GETRESUID              = 118
<span id="L128" class="ln">   128&nbsp;&nbsp;</span>	SYS_SETRESGID              = 119
<span id="L129" class="ln">   129&nbsp;&nbsp;</span>	SYS_GETRESGID              = 120
<span id="L130" class="ln">   130&nbsp;&nbsp;</span>	SYS_GETPGID                = 121
<span id="L131" class="ln">   131&nbsp;&nbsp;</span>	SYS_SETFSUID               = 122
<span id="L132" class="ln">   132&nbsp;&nbsp;</span>	SYS_SETFSGID               = 123
<span id="L133" class="ln">   133&nbsp;&nbsp;</span>	SYS_GETSID                 = 124
<span id="L134" class="ln">   134&nbsp;&nbsp;</span>	SYS_CAPGET                 = 125
<span id="L135" class="ln">   135&nbsp;&nbsp;</span>	SYS_CAPSET                 = 126
<span id="L136" class="ln">   136&nbsp;&nbsp;</span>	SYS_RT_SIGPENDING          = 127
<span id="L137" class="ln">   137&nbsp;&nbsp;</span>	SYS_RT_SIGTIMEDWAIT        = 128
<span id="L138" class="ln">   138&nbsp;&nbsp;</span>	SYS_RT_SIGQUEUEINFO        = 129
<span id="L139" class="ln">   139&nbsp;&nbsp;</span>	SYS_RT_SIGSUSPEND          = 130
<span id="L140" class="ln">   140&nbsp;&nbsp;</span>	SYS_SIGALTSTACK            = 131
<span id="L141" class="ln">   141&nbsp;&nbsp;</span>	SYS_UTIME                  = 132
<span id="L142" class="ln">   142&nbsp;&nbsp;</span>	SYS_MKNOD                  = 133
<span id="L143" class="ln">   143&nbsp;&nbsp;</span>	SYS_USELIB                 = 134
<span id="L144" class="ln">   144&nbsp;&nbsp;</span>	SYS_PERSONALITY            = 135
<span id="L145" class="ln">   145&nbsp;&nbsp;</span>	SYS_USTAT                  = 136
<span id="L146" class="ln">   146&nbsp;&nbsp;</span>	SYS_STATFS                 = 137
<span id="L147" class="ln">   147&nbsp;&nbsp;</span>	SYS_FSTATFS                = 138
<span id="L148" class="ln">   148&nbsp;&nbsp;</span>	SYS_SYSFS                  = 139
<span id="L149" class="ln">   149&nbsp;&nbsp;</span>	SYS_GETPRIORITY            = 140
<span id="L150" class="ln">   150&nbsp;&nbsp;</span>	SYS_SETPRIORITY            = 141
<span id="L151" class="ln">   151&nbsp;&nbsp;</span>	SYS_SCHED_SETPARAM         = 142
<span id="L152" class="ln">   152&nbsp;&nbsp;</span>	SYS_SCHED_GETPARAM         = 143
<span id="L153" class="ln">   153&nbsp;&nbsp;</span>	SYS_SCHED_SETSCHEDULER     = 144
<span id="L154" class="ln">   154&nbsp;&nbsp;</span>	SYS_SCHED_GETSCHEDULER     = 145
<span id="L155" class="ln">   155&nbsp;&nbsp;</span>	SYS_SCHED_GET_PRIORITY_MAX = 146
<span id="L156" class="ln">   156&nbsp;&nbsp;</span>	SYS_SCHED_GET_PRIORITY_MIN = 147
<span id="L157" class="ln">   157&nbsp;&nbsp;</span>	SYS_SCHED_RR_GET_INTERVAL  = 148
<span id="L158" class="ln">   158&nbsp;&nbsp;</span>	SYS_MLOCK                  = 149
<span id="L159" class="ln">   159&nbsp;&nbsp;</span>	SYS_MUNLOCK                = 150
<span id="L160" class="ln">   160&nbsp;&nbsp;</span>	SYS_MLOCKALL               = 151
<span id="L161" class="ln">   161&nbsp;&nbsp;</span>	SYS_MUNLOCKALL             = 152
<span id="L162" class="ln">   162&nbsp;&nbsp;</span>	SYS_VHANGUP                = 153
<span id="L163" class="ln">   163&nbsp;&nbsp;</span>	SYS_MODIFY_LDT             = 154
<span id="L164" class="ln">   164&nbsp;&nbsp;</span>	SYS_PIVOT_ROOT             = 155
<span id="L165" class="ln">   165&nbsp;&nbsp;</span>	SYS__SYSCTL                = 156
<span id="L166" class="ln">   166&nbsp;&nbsp;</span>	SYS_PRCTL                  = 157
<span id="L167" class="ln">   167&nbsp;&nbsp;</span>	SYS_ARCH_PRCTL             = 158
<span id="L168" class="ln">   168&nbsp;&nbsp;</span>	SYS_ADJTIMEX               = 159
<span id="L169" class="ln">   169&nbsp;&nbsp;</span>	SYS_SETRLIMIT              = 160
<span id="L170" class="ln">   170&nbsp;&nbsp;</span>	SYS_CHROOT                 = 161
<span id="L171" class="ln">   171&nbsp;&nbsp;</span>	SYS_SYNC                   = 162
<span id="L172" class="ln">   172&nbsp;&nbsp;</span>	SYS_ACCT                   = 163
<span id="L173" class="ln">   173&nbsp;&nbsp;</span>	SYS_SETTIMEOFDAY           = 164
<span id="L174" class="ln">   174&nbsp;&nbsp;</span>	SYS_MOUNT                  = 165
<span id="L175" class="ln">   175&nbsp;&nbsp;</span>	SYS_UMOUNT2                = 166
<span id="L176" class="ln">   176&nbsp;&nbsp;</span>	SYS_SWAPON                 = 167
<span id="L177" class="ln">   177&nbsp;&nbsp;</span>	SYS_SWAPOFF                = 168
<span id="L178" class="ln">   178&nbsp;&nbsp;</span>	SYS_REBOOT                 = 169
<span id="L179" class="ln">   179&nbsp;&nbsp;</span>	SYS_SETHOSTNAME            = 170
<span id="L180" class="ln">   180&nbsp;&nbsp;</span>	SYS_SETDOMAINNAME          = 171
<span id="L181" class="ln">   181&nbsp;&nbsp;</span>	SYS_IOPL                   = 172
<span id="L182" class="ln">   182&nbsp;&nbsp;</span>	SYS_IOPERM                 = 173
<span id="L183" class="ln">   183&nbsp;&nbsp;</span>	SYS_CREATE_MODULE          = 174
<span id="L184" class="ln">   184&nbsp;&nbsp;</span>	SYS_INIT_MODULE            = 175
<span id="L185" class="ln">   185&nbsp;&nbsp;</span>	SYS_DELETE_MODULE          = 176
<span id="L186" class="ln">   186&nbsp;&nbsp;</span>	SYS_GET_KERNEL_SYMS        = 177
<span id="L187" class="ln">   187&nbsp;&nbsp;</span>	SYS_QUERY_MODULE           = 178
<span id="L188" class="ln">   188&nbsp;&nbsp;</span>	SYS_QUOTACTL               = 179
<span id="L189" class="ln">   189&nbsp;&nbsp;</span>	SYS_NFSSERVCTL             = 180
<span id="L190" class="ln">   190&nbsp;&nbsp;</span>	SYS_GETPMSG                = 181
<span id="L191" class="ln">   191&nbsp;&nbsp;</span>	SYS_PUTPMSG                = 182
<span id="L192" class="ln">   192&nbsp;&nbsp;</span>	SYS_AFS_SYSCALL            = 183
<span id="L193" class="ln">   193&nbsp;&nbsp;</span>	SYS_TUXCALL                = 184
<span id="L194" class="ln">   194&nbsp;&nbsp;</span>	SYS_SECURITY               = 185
<span id="L195" class="ln">   195&nbsp;&nbsp;</span>	SYS_GETTID                 = 186
<span id="L196" class="ln">   196&nbsp;&nbsp;</span>	SYS_READAHEAD              = 187
<span id="L197" class="ln">   197&nbsp;&nbsp;</span>	SYS_SETXATTR               = 188
<span id="L198" class="ln">   198&nbsp;&nbsp;</span>	SYS_LSETXATTR              = 189
<span id="L199" class="ln">   199&nbsp;&nbsp;</span>	SYS_FSETXATTR              = 190
<span id="L200" class="ln">   200&nbsp;&nbsp;</span>	SYS_GETXATTR               = 191
<span id="L201" class="ln">   201&nbsp;&nbsp;</span>	SYS_LGETXATTR              = 192
<span id="L202" class="ln">   202&nbsp;&nbsp;</span>	SYS_FGETXATTR              = 193
<span id="L203" class="ln">   203&nbsp;&nbsp;</span>	SYS_LISTXATTR              = 194
<span id="L204" class="ln">   204&nbsp;&nbsp;</span>	SYS_LLISTXATTR             = 195
<span id="L205" class="ln">   205&nbsp;&nbsp;</span>	SYS_FLISTXATTR             = 196
<span id="L206" class="ln">   206&nbsp;&nbsp;</span>	SYS_REMOVEXATTR            = 197
<span id="L207" class="ln">   207&nbsp;&nbsp;</span>	SYS_LREMOVEXATTR           = 198
<span id="L208" class="ln">   208&nbsp;&nbsp;</span>	SYS_FREMOVEXATTR           = 199
<span id="L209" class="ln">   209&nbsp;&nbsp;</span>	SYS_TKILL                  = 200
<span id="L210" class="ln">   210&nbsp;&nbsp;</span>	SYS_TIME                   = 201
<span id="L211" class="ln">   211&nbsp;&nbsp;</span>	SYS_FUTEX                  = 202
<span id="L212" class="ln">   212&nbsp;&nbsp;</span>	SYS_SCHED_SETAFFINITY      = 203
<span id="L213" class="ln">   213&nbsp;&nbsp;</span>	SYS_SCHED_GETAFFINITY      = 204
<span id="L214" class="ln">   214&nbsp;&nbsp;</span>	SYS_SET_THREAD_AREA        = 205
<span id="L215" class="ln">   215&nbsp;&nbsp;</span>	SYS_IO_SETUP               = 206
<span id="L216" class="ln">   216&nbsp;&nbsp;</span>	SYS_IO_DESTROY             = 207
<span id="L217" class="ln">   217&nbsp;&nbsp;</span>	SYS_IO_GETEVENTS           = 208
<span id="L218" class="ln">   218&nbsp;&nbsp;</span>	SYS_IO_SUBMIT              = 209
<span id="L219" class="ln">   219&nbsp;&nbsp;</span>	SYS_IO_CANCEL              = 210
<span id="L220" class="ln">   220&nbsp;&nbsp;</span>	SYS_GET_THREAD_AREA        = 211
<span id="L221" class="ln">   221&nbsp;&nbsp;</span>	SYS_LOOKUP_DCOOKIE         = 212
<span id="L222" class="ln">   222&nbsp;&nbsp;</span>	SYS_EPOLL_CREATE           = 213
<span id="L223" class="ln">   223&nbsp;&nbsp;</span>	SYS_EPOLL_CTL_OLD          = 214
<span id="L224" class="ln">   224&nbsp;&nbsp;</span>	SYS_EPOLL_WAIT_OLD         = 215
<span id="L225" class="ln">   225&nbsp;&nbsp;</span>	SYS_REMAP_FILE_PAGES       = 216
<span id="L226" class="ln">   226&nbsp;&nbsp;</span>	SYS_GETDENTS64             = 217
<span id="L227" class="ln">   227&nbsp;&nbsp;</span>	SYS_SET_TID_ADDRESS        = 218
<span id="L228" class="ln">   228&nbsp;&nbsp;</span>	SYS_RESTART_SYSCALL        = 219
<span id="L229" class="ln">   229&nbsp;&nbsp;</span>	SYS_SEMTIMEDOP             = 220
<span id="L230" class="ln">   230&nbsp;&nbsp;</span>	SYS_FADVISE64              = 221
<span id="L231" class="ln">   231&nbsp;&nbsp;</span>	SYS_TIMER_CREATE           = 222
<span id="L232" class="ln">   232&nbsp;&nbsp;</span>	SYS_TIMER_SETTIME          = 223
<span id="L233" class="ln">   233&nbsp;&nbsp;</span>	SYS_TIMER_GETTIME          = 224
<span id="L234" class="ln">   234&nbsp;&nbsp;</span>	SYS_TIMER_GETOVERRUN       = 225
<span id="L235" class="ln">   235&nbsp;&nbsp;</span>	SYS_TIMER_DELETE           = 226
<span id="L236" class="ln">   236&nbsp;&nbsp;</span>	SYS_CLOCK_SETTIME          = 227
<span id="L237" class="ln">   237&nbsp;&nbsp;</span>	SYS_CLOCK_GETTIME          = 228
<span id="L238" class="ln">   238&nbsp;&nbsp;</span>	SYS_CLOCK_GETRES           = 229
<span id="L239" class="ln">   239&nbsp;&nbsp;</span>	SYS_CLOCK_NANOSLEEP        = 230
<span id="L240" class="ln">   240&nbsp;&nbsp;</span>	SYS_EXIT_GROUP             = 231
<span id="L241" class="ln">   241&nbsp;&nbsp;</span>	SYS_EPOLL_WAIT             = 232
<span id="L242" class="ln">   242&nbsp;&nbsp;</span>	SYS_EPOLL_CTL              = 233
<span id="L243" class="ln">   243&nbsp;&nbsp;</span>	SYS_TGKILL                 = 234
<span id="L244" class="ln">   244&nbsp;&nbsp;</span>	SYS_UTIMES                 = 235
<span id="L245" class="ln">   245&nbsp;&nbsp;</span>	SYS_VSERVER                = 236
<span id="L246" class="ln">   246&nbsp;&nbsp;</span>	SYS_MBIND                  = 237
<span id="L247" class="ln">   247&nbsp;&nbsp;</span>	SYS_SET_MEMPOLICY          = 238
<span id="L248" class="ln">   248&nbsp;&nbsp;</span>	SYS_GET_MEMPOLICY          = 239
<span id="L249" class="ln">   249&nbsp;&nbsp;</span>	SYS_MQ_OPEN                = 240
<span id="L250" class="ln">   250&nbsp;&nbsp;</span>	SYS_MQ_UNLINK              = 241
<span id="L251" class="ln">   251&nbsp;&nbsp;</span>	SYS_MQ_TIMEDSEND           = 242
<span id="L252" class="ln">   252&nbsp;&nbsp;</span>	SYS_MQ_TIMEDRECEIVE        = 243
<span id="L253" class="ln">   253&nbsp;&nbsp;</span>	SYS_MQ_NOTIFY              = 244
<span id="L254" class="ln">   254&nbsp;&nbsp;</span>	SYS_MQ_GETSETATTR          = 245
<span id="L255" class="ln">   255&nbsp;&nbsp;</span>	SYS_KEXEC_LOAD             = 246
<span id="L256" class="ln">   256&nbsp;&nbsp;</span>	SYS_WAITID                 = 247
<span id="L257" class="ln">   257&nbsp;&nbsp;</span>	SYS_ADD_KEY                = 248
<span id="L258" class="ln">   258&nbsp;&nbsp;</span>	SYS_REQUEST_KEY            = 249
<span id="L259" class="ln">   259&nbsp;&nbsp;</span>	SYS_KEYCTL                 = 250
<span id="L260" class="ln">   260&nbsp;&nbsp;</span>	SYS_IOPRIO_SET             = 251
<span id="L261" class="ln">   261&nbsp;&nbsp;</span>	SYS_IOPRIO_GET             = 252
<span id="L262" class="ln">   262&nbsp;&nbsp;</span>	SYS_INOTIFY_INIT           = 253
<span id="L263" class="ln">   263&nbsp;&nbsp;</span>	SYS_INOTIFY_ADD_WATCH      = 254
<span id="L264" class="ln">   264&nbsp;&nbsp;</span>	SYS_INOTIFY_RM_WATCH       = 255
<span id="L265" class="ln">   265&nbsp;&nbsp;</span>	SYS_MIGRATE_PAGES          = 256
<span id="L266" class="ln">   266&nbsp;&nbsp;</span>	SYS_OPENAT                 = 257
<span id="L267" class="ln">   267&nbsp;&nbsp;</span>	SYS_MKDIRAT                = 258
<span id="L268" class="ln">   268&nbsp;&nbsp;</span>	SYS_MKNODAT                = 259
<span id="L269" class="ln">   269&nbsp;&nbsp;</span>	SYS_FCHOWNAT               = 260
<span id="L270" class="ln">   270&nbsp;&nbsp;</span>	SYS_FUTIMESAT              = 261
<span id="L271" class="ln">   271&nbsp;&nbsp;</span>	SYS_NEWFSTATAT             = 262
<span id="L272" class="ln">   272&nbsp;&nbsp;</span>	SYS_UNLINKAT               = 263
<span id="L273" class="ln">   273&nbsp;&nbsp;</span>	SYS_RENAMEAT               = 264
<span id="L274" class="ln">   274&nbsp;&nbsp;</span>	SYS_LINKAT                 = 265
<span id="L275" class="ln">   275&nbsp;&nbsp;</span>	SYS_SYMLINKAT              = 266
<span id="L276" class="ln">   276&nbsp;&nbsp;</span>	SYS_READLINKAT             = 267
<span id="L277" class="ln">   277&nbsp;&nbsp;</span>	SYS_FCHMODAT               = 268
<span id="L278" class="ln">   278&nbsp;&nbsp;</span>	SYS_FACCESSAT              = 269
<span id="L279" class="ln">   279&nbsp;&nbsp;</span>	SYS_PSELECT6               = 270
<span id="L280" class="ln">   280&nbsp;&nbsp;</span>	SYS_PPOLL                  = 271
<span id="L281" class="ln">   281&nbsp;&nbsp;</span>	SYS_UNSHARE                = 272
<span id="L282" class="ln">   282&nbsp;&nbsp;</span>	SYS_SET_ROBUST_LIST        = 273
<span id="L283" class="ln">   283&nbsp;&nbsp;</span>	SYS_GET_ROBUST_LIST        = 274
<span id="L284" class="ln">   284&nbsp;&nbsp;</span>	SYS_SPLICE                 = 275
<span id="L285" class="ln">   285&nbsp;&nbsp;</span>	SYS_TEE                    = 276
<span id="L286" class="ln">   286&nbsp;&nbsp;</span>	SYS_SYNC_FILE_RANGE        = 277
<span id="L287" class="ln">   287&nbsp;&nbsp;</span>	SYS_VMSPLICE               = 278
<span id="L288" class="ln">   288&nbsp;&nbsp;</span>	SYS_MOVE_PAGES             = 279
<span id="L289" class="ln">   289&nbsp;&nbsp;</span>	SYS_UTIMENSAT              = 280
<span id="L290" class="ln">   290&nbsp;&nbsp;</span>	SYS_EPOLL_PWAIT            = 281
<span id="L291" class="ln">   291&nbsp;&nbsp;</span>	SYS_SIGNALFD               = 282
<span id="L292" class="ln">   292&nbsp;&nbsp;</span>	SYS_TIMERFD_CREATE         = 283
<span id="L293" class="ln">   293&nbsp;&nbsp;</span>	SYS_EVENTFD                = 284
<span id="L294" class="ln">   294&nbsp;&nbsp;</span>	SYS_FALLOCATE              = 285
<span id="L295" class="ln">   295&nbsp;&nbsp;</span>	SYS_TIMERFD_SETTIME        = 286
<span id="L296" class="ln">   296&nbsp;&nbsp;</span>	SYS_TIMERFD_GETTIME        = 287
<span id="L297" class="ln">   297&nbsp;&nbsp;</span>	SYS_ACCEPT4                = 288
<span id="L298" class="ln">   298&nbsp;&nbsp;</span>	SYS_SIGNALFD4              = 289
<span id="L299" class="ln">   299&nbsp;&nbsp;</span>	SYS_EVENTFD2               = 290
<span id="L300" class="ln">   300&nbsp;&nbsp;</span>	SYS_EPOLL_CREATE1          = 291
<span id="L301" class="ln">   301&nbsp;&nbsp;</span>	SYS_DUP3                   = 292
<span id="L302" class="ln">   302&nbsp;&nbsp;</span>	SYS_PIPE2                  = 293
<span id="L303" class="ln">   303&nbsp;&nbsp;</span>	SYS_INOTIFY_INIT1          = 294
<span id="L304" class="ln">   304&nbsp;&nbsp;</span>	SYS_PREADV                 = 295
<span id="L305" class="ln">   305&nbsp;&nbsp;</span>	SYS_PWRITEV                = 296
<span id="L306" class="ln">   306&nbsp;&nbsp;</span>	SYS_RT_TGSIGQUEUEINFO      = 297
<span id="L307" class="ln">   307&nbsp;&nbsp;</span>	SYS_PERF_EVENT_OPEN        = 298
<span id="L308" class="ln">   308&nbsp;&nbsp;</span>	SYS_RECVMMSG               = 299
<span id="L309" class="ln">   309&nbsp;&nbsp;</span>	SYS_FANOTIFY_INIT          = 300
<span id="L310" class="ln">   310&nbsp;&nbsp;</span>	SYS_FANOTIFY_MARK          = 301
<span id="L311" class="ln">   311&nbsp;&nbsp;</span>	SYS_PRLIMIT64              = 302
<span id="L312" class="ln">   312&nbsp;&nbsp;</span>)
<span id="L313" class="ln">   313&nbsp;&nbsp;</span>
</pre><p><a href="zsysnum_linux_amd64.go?m=text">View as plain text</a></p>

<div id="footer">
Build version go1.22.2.<br>
Except as <a href="https://developers.google.com/site-policies#restrictions">noted</a>,
the content of this page is licensed under the
Creative Commons Attribution 3.0 License,
and code is licensed under a <a href="http://localhost:8080/LICENSE">BSD license</a>.<br>
<a href="https://golang.org/doc/tos.html">Terms of Service</a> |
<a href="https://www.google.com/intl/en/policies/privacy/">Privacy Policy</a>
</div>

</div><!-- .container -->
</div><!-- #page -->
</body>
</html>
