<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#375EAB">

  <title>src/runtime/sizeclasses.go - Go Documentation Server</title>

<link type="text/css" rel="stylesheet" href="../../lib/godoc/style.css">

<script>window.initFuncs = [];</script>
<script src="../../lib/godoc/jquery.js" defer></script>



<script>var goVersion = "go1.22.2";</script>
<script src="../../lib/godoc/godocs.js" defer></script>
</head>
<body>

<div id='lowframe' style="position: fixed; bottom: 0; left: 0; height: 0; width: 100%; border-top: thin solid grey; background-color: white; overflow: auto;">
...
</div><!-- #lowframe -->

<div id="topbar" class="wide"><div class="container">
<div class="top-heading" id="heading-wide"><a href="../../index.html">Go Documentation Server</a></div>
<div class="top-heading" id="heading-narrow"><a href="../../index.html">GoDoc</a></div>
<a href="sizeclasses.go#" id="menu-button"><span id="menu-button-arrow">&#9661;</span></a>
<form method="GET" action="http://localhost:8080/search">
<div id="menu">

<span class="search-box"><input type="search" id="search" name="q" placeholder="Search" aria-label="Search" required><button type="submit"><span><!-- magnifying glass: --><svg width="24" height="24" viewBox="0 0 24 24"><title>submit search</title><path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/><path d="M0 0h24v24H0z" fill="none"/></svg></span></button></span>
</div>
</form>

</div></div>



<div id="page" class="wide">
<div class="container">


  <h1>
    Source file
    <a href="http://localhost:8080/src">src</a>/<a href="http://localhost:8080/src/runtime">runtime</a>/<span class="text-muted">sizeclasses.go</span>
  </h1>





  <h2>
    Documentation: <a href="http://localhost:8080/pkg/runtime">runtime</a>
  </h2>



<div id="nav"></div>


<script type='text/javascript'>document.ANALYSIS_DATA = null;</script>
<pre><span id="L1" class="ln">     1&nbsp;&nbsp;</span><span class="comment">// Code generated by mksizeclasses.go; DO NOT EDIT.</span>
<span id="L2" class="ln">     2&nbsp;&nbsp;</span><span class="comment">//go:generate go run mksizeclasses.go</span>
<span id="L3" class="ln">     3&nbsp;&nbsp;</span>
<span id="L4" class="ln">     4&nbsp;&nbsp;</span>package runtime
<span id="L5" class="ln">     5&nbsp;&nbsp;</span>
<span id="L6" class="ln">     6&nbsp;&nbsp;</span><span class="comment">// class  bytes/obj  bytes/span  objects  tail waste  max waste  min align</span>
<span id="L7" class="ln">     7&nbsp;&nbsp;</span><span class="comment">//     1          8        8192     1024           0     87.50%          8</span>
<span id="L8" class="ln">     8&nbsp;&nbsp;</span><span class="comment">//     2         16        8192      512           0     43.75%         16</span>
<span id="L9" class="ln">     9&nbsp;&nbsp;</span><span class="comment">//     3         24        8192      341           8     29.24%          8</span>
<span id="L10" class="ln">    10&nbsp;&nbsp;</span><span class="comment">//     4         32        8192      256           0     21.88%         32</span>
<span id="L11" class="ln">    11&nbsp;&nbsp;</span><span class="comment">//     5         48        8192      170          32     31.52%         16</span>
<span id="L12" class="ln">    12&nbsp;&nbsp;</span><span class="comment">//     6         64        8192      128           0     23.44%         64</span>
<span id="L13" class="ln">    13&nbsp;&nbsp;</span><span class="comment">//     7         80        8192      102          32     19.07%         16</span>
<span id="L14" class="ln">    14&nbsp;&nbsp;</span><span class="comment">//     8         96        8192       85          32     15.95%         32</span>
<span id="L15" class="ln">    15&nbsp;&nbsp;</span><span class="comment">//     9        112        8192       73          16     13.56%         16</span>
<span id="L16" class="ln">    16&nbsp;&nbsp;</span><span class="comment">//    10        128        8192       64           0     11.72%        128</span>
<span id="L17" class="ln">    17&nbsp;&nbsp;</span><span class="comment">//    11        144        8192       56         128     11.82%         16</span>
<span id="L18" class="ln">    18&nbsp;&nbsp;</span><span class="comment">//    12        160        8192       51          32      9.73%         32</span>
<span id="L19" class="ln">    19&nbsp;&nbsp;</span><span class="comment">//    13        176        8192       46          96      9.59%         16</span>
<span id="L20" class="ln">    20&nbsp;&nbsp;</span><span class="comment">//    14        192        8192       42         128      9.25%         64</span>
<span id="L21" class="ln">    21&nbsp;&nbsp;</span><span class="comment">//    15        208        8192       39          80      8.12%         16</span>
<span id="L22" class="ln">    22&nbsp;&nbsp;</span><span class="comment">//    16        224        8192       36         128      8.15%         32</span>
<span id="L23" class="ln">    23&nbsp;&nbsp;</span><span class="comment">//    17        240        8192       34          32      6.62%         16</span>
<span id="L24" class="ln">    24&nbsp;&nbsp;</span><span class="comment">//    18        256        8192       32           0      5.86%        256</span>
<span id="L25" class="ln">    25&nbsp;&nbsp;</span><span class="comment">//    19        288        8192       28         128     12.16%         32</span>
<span id="L26" class="ln">    26&nbsp;&nbsp;</span><span class="comment">//    20        320        8192       25         192     11.80%         64</span>
<span id="L27" class="ln">    27&nbsp;&nbsp;</span><span class="comment">//    21        352        8192       23          96      9.88%         32</span>
<span id="L28" class="ln">    28&nbsp;&nbsp;</span><span class="comment">//    22        384        8192       21         128      9.51%        128</span>
<span id="L29" class="ln">    29&nbsp;&nbsp;</span><span class="comment">//    23        416        8192       19         288     10.71%         32</span>
<span id="L30" class="ln">    30&nbsp;&nbsp;</span><span class="comment">//    24        448        8192       18         128      8.37%         64</span>
<span id="L31" class="ln">    31&nbsp;&nbsp;</span><span class="comment">//    25        480        8192       17          32      6.82%         32</span>
<span id="L32" class="ln">    32&nbsp;&nbsp;</span><span class="comment">//    26        512        8192       16           0      6.05%        512</span>
<span id="L33" class="ln">    33&nbsp;&nbsp;</span><span class="comment">//    27        576        8192       14         128     12.33%         64</span>
<span id="L34" class="ln">    34&nbsp;&nbsp;</span><span class="comment">//    28        640        8192       12         512     15.48%        128</span>
<span id="L35" class="ln">    35&nbsp;&nbsp;</span><span class="comment">//    29        704        8192       11         448     13.93%         64</span>
<span id="L36" class="ln">    36&nbsp;&nbsp;</span><span class="comment">//    30        768        8192       10         512     13.94%        256</span>
<span id="L37" class="ln">    37&nbsp;&nbsp;</span><span class="comment">//    31        896        8192        9         128     15.52%        128</span>
<span id="L38" class="ln">    38&nbsp;&nbsp;</span><span class="comment">//    32       1024        8192        8           0     12.40%       1024</span>
<span id="L39" class="ln">    39&nbsp;&nbsp;</span><span class="comment">//    33       1152        8192        7         128     12.41%        128</span>
<span id="L40" class="ln">    40&nbsp;&nbsp;</span><span class="comment">//    34       1280        8192        6         512     15.55%        256</span>
<span id="L41" class="ln">    41&nbsp;&nbsp;</span><span class="comment">//    35       1408       16384       11         896     14.00%        128</span>
<span id="L42" class="ln">    42&nbsp;&nbsp;</span><span class="comment">//    36       1536        8192        5         512     14.00%        512</span>
<span id="L43" class="ln">    43&nbsp;&nbsp;</span><span class="comment">//    37       1792       16384        9         256     15.57%        256</span>
<span id="L44" class="ln">    44&nbsp;&nbsp;</span><span class="comment">//    38       2048        8192        4           0     12.45%       2048</span>
<span id="L45" class="ln">    45&nbsp;&nbsp;</span><span class="comment">//    39       2304       16384        7         256     12.46%        256</span>
<span id="L46" class="ln">    46&nbsp;&nbsp;</span><span class="comment">//    40       2688        8192        3         128     15.59%        128</span>
<span id="L47" class="ln">    47&nbsp;&nbsp;</span><span class="comment">//    41       3072       24576        8           0     12.47%       1024</span>
<span id="L48" class="ln">    48&nbsp;&nbsp;</span><span class="comment">//    42       3200       16384        5         384      6.22%        128</span>
<span id="L49" class="ln">    49&nbsp;&nbsp;</span><span class="comment">//    43       3456       24576        7         384      8.83%        128</span>
<span id="L50" class="ln">    50&nbsp;&nbsp;</span><span class="comment">//    44       4096        8192        2           0     15.60%       4096</span>
<span id="L51" class="ln">    51&nbsp;&nbsp;</span><span class="comment">//    45       4864       24576        5         256     16.65%        256</span>
<span id="L52" class="ln">    52&nbsp;&nbsp;</span><span class="comment">//    46       5376       16384        3         256     10.92%        256</span>
<span id="L53" class="ln">    53&nbsp;&nbsp;</span><span class="comment">//    47       6144       24576        4           0     12.48%       2048</span>
<span id="L54" class="ln">    54&nbsp;&nbsp;</span><span class="comment">//    48       6528       32768        5         128      6.23%        128</span>
<span id="L55" class="ln">    55&nbsp;&nbsp;</span><span class="comment">//    49       6784       40960        6         256      4.36%        128</span>
<span id="L56" class="ln">    56&nbsp;&nbsp;</span><span class="comment">//    50       6912       49152        7         768      3.37%        256</span>
<span id="L57" class="ln">    57&nbsp;&nbsp;</span><span class="comment">//    51       8192        8192        1           0     15.61%       8192</span>
<span id="L58" class="ln">    58&nbsp;&nbsp;</span><span class="comment">//    52       9472       57344        6         512     14.28%        256</span>
<span id="L59" class="ln">    59&nbsp;&nbsp;</span><span class="comment">//    53       9728       49152        5         512      3.64%        512</span>
<span id="L60" class="ln">    60&nbsp;&nbsp;</span><span class="comment">//    54      10240       40960        4           0      4.99%       2048</span>
<span id="L61" class="ln">    61&nbsp;&nbsp;</span><span class="comment">//    55      10880       32768        3         128      6.24%        128</span>
<span id="L62" class="ln">    62&nbsp;&nbsp;</span><span class="comment">//    56      12288       24576        2           0     11.45%       4096</span>
<span id="L63" class="ln">    63&nbsp;&nbsp;</span><span class="comment">//    57      13568       40960        3         256      9.99%        256</span>
<span id="L64" class="ln">    64&nbsp;&nbsp;</span><span class="comment">//    58      14336       57344        4           0      5.35%       2048</span>
<span id="L65" class="ln">    65&nbsp;&nbsp;</span><span class="comment">//    59      16384       16384        1           0     12.49%       8192</span>
<span id="L66" class="ln">    66&nbsp;&nbsp;</span><span class="comment">//    60      18432       73728        4           0     11.11%       2048</span>
<span id="L67" class="ln">    67&nbsp;&nbsp;</span><span class="comment">//    61      19072       57344        3         128      3.57%        128</span>
<span id="L68" class="ln">    68&nbsp;&nbsp;</span><span class="comment">//    62      20480       40960        2           0      6.87%       4096</span>
<span id="L69" class="ln">    69&nbsp;&nbsp;</span><span class="comment">//    63      21760       65536        3         256      6.25%        256</span>
<span id="L70" class="ln">    70&nbsp;&nbsp;</span><span class="comment">//    64      24576       24576        1           0     11.45%       8192</span>
<span id="L71" class="ln">    71&nbsp;&nbsp;</span><span class="comment">//    65      27264       81920        3         128     10.00%        128</span>
<span id="L72" class="ln">    72&nbsp;&nbsp;</span><span class="comment">//    66      28672       57344        2           0      4.91%       4096</span>
<span id="L73" class="ln">    73&nbsp;&nbsp;</span><span class="comment">//    67      32768       32768        1           0     12.50%       8192</span>
<span id="L74" class="ln">    74&nbsp;&nbsp;</span>
<span id="L75" class="ln">    75&nbsp;&nbsp;</span><span class="comment">// alignment  bits  min obj size</span>
<span id="L76" class="ln">    76&nbsp;&nbsp;</span><span class="comment">//         8     3             8</span>
<span id="L77" class="ln">    77&nbsp;&nbsp;</span><span class="comment">//        16     4            32</span>
<span id="L78" class="ln">    78&nbsp;&nbsp;</span><span class="comment">//        32     5           256</span>
<span id="L79" class="ln">    79&nbsp;&nbsp;</span><span class="comment">//        64     6           512</span>
<span id="L80" class="ln">    80&nbsp;&nbsp;</span><span class="comment">//       128     7           768</span>
<span id="L81" class="ln">    81&nbsp;&nbsp;</span><span class="comment">//      4096    12         28672</span>
<span id="L82" class="ln">    82&nbsp;&nbsp;</span><span class="comment">//      8192    13         32768</span>
<span id="L83" class="ln">    83&nbsp;&nbsp;</span>
<span id="L84" class="ln">    84&nbsp;&nbsp;</span>const (
<span id="L85" class="ln">    85&nbsp;&nbsp;</span>	_MaxSmallSize   = 32768
<span id="L86" class="ln">    86&nbsp;&nbsp;</span>	smallSizeDiv    = 8
<span id="L87" class="ln">    87&nbsp;&nbsp;</span>	smallSizeMax    = 1024
<span id="L88" class="ln">    88&nbsp;&nbsp;</span>	largeSizeDiv    = 128
<span id="L89" class="ln">    89&nbsp;&nbsp;</span>	_NumSizeClasses = 68
<span id="L90" class="ln">    90&nbsp;&nbsp;</span>	_PageShift      = 13
<span id="L91" class="ln">    91&nbsp;&nbsp;</span>	maxObjsPerSpan  = 1024
<span id="L92" class="ln">    92&nbsp;&nbsp;</span>)
<span id="L93" class="ln">    93&nbsp;&nbsp;</span>
<span id="L94" class="ln">    94&nbsp;&nbsp;</span>var class_to_size = [_NumSizeClasses]uint16{0, 8, 16, 24, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240, 256, 288, 320, 352, 384, 416, 448, 480, 512, 576, 640, 704, 768, 896, 1024, 1152, 1280, 1408, 1536, 1792, 2048, 2304, 2688, 3072, 3200, 3456, 4096, 4864, 5376, 6144, 6528, 6784, 6912, 8192, 9472, 9728, 10240, 10880, 12288, 13568, 14336, 16384, 18432, 19072, 20480, 21760, 24576, 27264, 28672, 32768}
<span id="L95" class="ln">    95&nbsp;&nbsp;</span>var class_to_allocnpages = [_NumSizeClasses]uint8{0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 3, 2, 3, 1, 3, 2, 3, 4, 5, 6, 1, 7, 6, 5, 4, 3, 5, 7, 2, 9, 7, 5, 8, 3, 10, 7, 4}
<span id="L96" class="ln">    96&nbsp;&nbsp;</span>var class_to_divmagic = [_NumSizeClasses]uint32{0, ^uint32(0)/8 + 1, ^uint32(0)/16 + 1, ^uint32(0)/24 + 1, ^uint32(0)/32 + 1, ^uint32(0)/48 + 1, ^uint32(0)/64 + 1, ^uint32(0)/80 + 1, ^uint32(0)/96 + 1, ^uint32(0)/112 + 1, ^uint32(0)/128 + 1, ^uint32(0)/144 + 1, ^uint32(0)/160 + 1, ^uint32(0)/176 + 1, ^uint32(0)/192 + 1, ^uint32(0)/208 + 1, ^uint32(0)/224 + 1, ^uint32(0)/240 + 1, ^uint32(0)/256 + 1, ^uint32(0)/288 + 1, ^uint32(0)/320 + 1, ^uint32(0)/352 + 1, ^uint32(0)/384 + 1, ^uint32(0)/416 + 1, ^uint32(0)/448 + 1, ^uint32(0)/480 + 1, ^uint32(0)/512 + 1, ^uint32(0)/576 + 1, ^uint32(0)/640 + 1, ^uint32(0)/704 + 1, ^uint32(0)/768 + 1, ^uint32(0)/896 + 1, ^uint32(0)/1024 + 1, ^uint32(0)/1152 + 1, ^uint32(0)/1280 + 1, ^uint32(0)/1408 + 1, ^uint32(0)/1536 + 1, ^uint32(0)/1792 + 1, ^uint32(0)/2048 + 1, ^uint32(0)/2304 + 1, ^uint32(0)/2688 + 1, ^uint32(0)/3072 + 1, ^uint32(0)/3200 + 1, ^uint32(0)/3456 + 1, ^uint32(0)/4096 + 1, ^uint32(0)/4864 + 1, ^uint32(0)/5376 + 1, ^uint32(0)/6144 + 1, ^uint32(0)/6528 + 1, ^uint32(0)/6784 + 1, ^uint32(0)/6912 + 1, ^uint32(0)/8192 + 1, ^uint32(0)/9472 + 1, ^uint32(0)/9728 + 1, ^uint32(0)/10240 + 1, ^uint32(0)/10880 + 1, ^uint32(0)/12288 + 1, ^uint32(0)/13568 + 1, ^uint32(0)/14336 + 1, ^uint32(0)/16384 + 1, ^uint32(0)/18432 + 1, ^uint32(0)/19072 + 1, ^uint32(0)/20480 + 1, ^uint32(0)/21760 + 1, ^uint32(0)/24576 + 1, ^uint32(0)/27264 + 1, ^uint32(0)/28672 + 1, ^uint32(0)/32768 + 1}
<span id="L97" class="ln">    97&nbsp;&nbsp;</span>var size_to_class8 = [smallSizeMax/smallSizeDiv + 1]uint8{0, 1, 2, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 23, 23, 23, 23, 24, 24, 24, 24, 25, 25, 25, 25, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32}
<span id="L98" class="ln">    98&nbsp;&nbsp;</span>var size_to_class128 = [(_MaxSmallSize-smallSizeMax)/largeSizeDiv + 1]uint8{32, 33, 34, 35, 36, 37, 37, 38, 38, 39, 39, 40, 40, 40, 41, 41, 41, 42, 43, 43, 44, 44, 44, 44, 44, 45, 45, 45, 45, 45, 45, 46, 46, 46, 46, 47, 47, 47, 47, 47, 47, 48, 48, 48, 49, 49, 50, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 53, 53, 54, 54, 54, 54, 55, 55, 55, 55, 55, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 58, 58, 58, 58, 58, 58, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 61, 61, 61, 61, 61, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67}
<span id="L99" class="ln">    99&nbsp;&nbsp;</span>
</pre><p><a href="sizeclasses.go?m=text">View as plain text</a></p>

<div id="footer">
Build version go1.22.2.<br>
Except as <a href="https://developers.google.com/site-policies#restrictions">noted</a>,
the content of this page is licensed under the
Creative Commons Attribution 3.0 License,
and code is licensed under a <a href="http://localhost:8080/LICENSE">BSD license</a>.<br>
<a href="https://golang.org/doc/tos.html">Terms of Service</a> |
<a href="https://www.google.com/intl/en/policies/privacy/">Privacy Policy</a>
</div>

</div><!-- .container -->
</div><!-- #page -->
</body>
</html>
