<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#375EAB">

  <title>src/debug/dwarf/attr_string.go - Go Documentation Server</title>

<link type="text/css" rel="stylesheet" href="../../../lib/godoc/style.css">

<script>window.initFuncs = [];</script>
<script src="../../../lib/godoc/jquery.js" defer></script>



<script>var goVersion = "go1.22.2";</script>
<script src="../../../lib/godoc/godocs.js" defer></script>
</head>
<body>

<div id='lowframe' style="position: fixed; bottom: 0; left: 0; height: 0; width: 100%; border-top: thin solid grey; background-color: white; overflow: auto;">
...
</div><!-- #lowframe -->

<div id="topbar" class="wide"><div class="container">
<div class="top-heading" id="heading-wide"><a href="../../../index.html">Go Documentation Server</a></div>
<div class="top-heading" id="heading-narrow"><a href="../../../index.html">GoDoc</a></div>
<a href="attr_string.go#" id="menu-button"><span id="menu-button-arrow">&#9661;</span></a>
<form method="GET" action="http://localhost:8080/search">
<div id="menu">

<span class="search-box"><input type="search" id="search" name="q" placeholder="Search" aria-label="Search" required><button type="submit"><span><!-- magnifying glass: --><svg width="24" height="24" viewBox="0 0 24 24"><title>submit search</title><path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/><path d="M0 0h24v24H0z" fill="none"/></svg></span></button></span>
</div>
</form>

</div></div>



<div id="page" class="wide">
<div class="container">


  <h1>
    Source file
    <a href="http://localhost:8080/src">src</a>/<a href="http://localhost:8080/src/debug">debug</a>/<a href="http://localhost:8080/src/debug/dwarf">dwarf</a>/<span class="text-muted">attr_string.go</span>
  </h1>





  <h2>
    Documentation: <a href="http://localhost:8080/pkg/debug/dwarf">debug/dwarf</a>
  </h2>



<div id="nav"></div>


<script type='text/javascript'>document.ANALYSIS_DATA = null;</script>
<pre><span id="L1" class="ln">     1&nbsp;&nbsp;</span><span class="comment">// Code generated by &#34;stringer -type Attr -trimprefix=Attr&#34;; DO NOT EDIT.</span>
<span id="L2" class="ln">     2&nbsp;&nbsp;</span>
<span id="L3" class="ln">     3&nbsp;&nbsp;</span>package dwarf
<span id="L4" class="ln">     4&nbsp;&nbsp;</span>
<span id="L5" class="ln">     5&nbsp;&nbsp;</span>import &#34;strconv&#34;
<span id="L6" class="ln">     6&nbsp;&nbsp;</span>
<span id="L7" class="ln">     7&nbsp;&nbsp;</span>func _() {
<span id="L8" class="ln">     8&nbsp;&nbsp;</span>	<span class="comment">// An &#34;invalid array index&#34; compiler error signifies that the constant values have changed.</span>
<span id="L9" class="ln">     9&nbsp;&nbsp;</span>	<span class="comment">// Re-run the stringer command to generate them again.</span>
<span id="L10" class="ln">    10&nbsp;&nbsp;</span>	var x [1]struct{}
<span id="L11" class="ln">    11&nbsp;&nbsp;</span>	_ = x[AttrSibling-1]
<span id="L12" class="ln">    12&nbsp;&nbsp;</span>	_ = x[AttrLocation-2]
<span id="L13" class="ln">    13&nbsp;&nbsp;</span>	_ = x[AttrName-3]
<span id="L14" class="ln">    14&nbsp;&nbsp;</span>	_ = x[AttrOrdering-9]
<span id="L15" class="ln">    15&nbsp;&nbsp;</span>	_ = x[AttrByteSize-11]
<span id="L16" class="ln">    16&nbsp;&nbsp;</span>	_ = x[AttrBitOffset-12]
<span id="L17" class="ln">    17&nbsp;&nbsp;</span>	_ = x[AttrBitSize-13]
<span id="L18" class="ln">    18&nbsp;&nbsp;</span>	_ = x[AttrStmtList-16]
<span id="L19" class="ln">    19&nbsp;&nbsp;</span>	_ = x[AttrLowpc-17]
<span id="L20" class="ln">    20&nbsp;&nbsp;</span>	_ = x[AttrHighpc-18]
<span id="L21" class="ln">    21&nbsp;&nbsp;</span>	_ = x[AttrLanguage-19]
<span id="L22" class="ln">    22&nbsp;&nbsp;</span>	_ = x[AttrDiscr-21]
<span id="L23" class="ln">    23&nbsp;&nbsp;</span>	_ = x[AttrDiscrValue-22]
<span id="L24" class="ln">    24&nbsp;&nbsp;</span>	_ = x[AttrVisibility-23]
<span id="L25" class="ln">    25&nbsp;&nbsp;</span>	_ = x[AttrImport-24]
<span id="L26" class="ln">    26&nbsp;&nbsp;</span>	_ = x[AttrStringLength-25]
<span id="L27" class="ln">    27&nbsp;&nbsp;</span>	_ = x[AttrCommonRef-26]
<span id="L28" class="ln">    28&nbsp;&nbsp;</span>	_ = x[AttrCompDir-27]
<span id="L29" class="ln">    29&nbsp;&nbsp;</span>	_ = x[AttrConstValue-28]
<span id="L30" class="ln">    30&nbsp;&nbsp;</span>	_ = x[AttrContainingType-29]
<span id="L31" class="ln">    31&nbsp;&nbsp;</span>	_ = x[AttrDefaultValue-30]
<span id="L32" class="ln">    32&nbsp;&nbsp;</span>	_ = x[AttrInline-32]
<span id="L33" class="ln">    33&nbsp;&nbsp;</span>	_ = x[AttrIsOptional-33]
<span id="L34" class="ln">    34&nbsp;&nbsp;</span>	_ = x[AttrLowerBound-34]
<span id="L35" class="ln">    35&nbsp;&nbsp;</span>	_ = x[AttrProducer-37]
<span id="L36" class="ln">    36&nbsp;&nbsp;</span>	_ = x[AttrPrototyped-39]
<span id="L37" class="ln">    37&nbsp;&nbsp;</span>	_ = x[AttrReturnAddr-42]
<span id="L38" class="ln">    38&nbsp;&nbsp;</span>	_ = x[AttrStartScope-44]
<span id="L39" class="ln">    39&nbsp;&nbsp;</span>	_ = x[AttrStrideSize-46]
<span id="L40" class="ln">    40&nbsp;&nbsp;</span>	_ = x[AttrUpperBound-47]
<span id="L41" class="ln">    41&nbsp;&nbsp;</span>	_ = x[AttrAbstractOrigin-49]
<span id="L42" class="ln">    42&nbsp;&nbsp;</span>	_ = x[AttrAccessibility-50]
<span id="L43" class="ln">    43&nbsp;&nbsp;</span>	_ = x[AttrAddrClass-51]
<span id="L44" class="ln">    44&nbsp;&nbsp;</span>	_ = x[AttrArtificial-52]
<span id="L45" class="ln">    45&nbsp;&nbsp;</span>	_ = x[AttrBaseTypes-53]
<span id="L46" class="ln">    46&nbsp;&nbsp;</span>	_ = x[AttrCalling-54]
<span id="L47" class="ln">    47&nbsp;&nbsp;</span>	_ = x[AttrCount-55]
<span id="L48" class="ln">    48&nbsp;&nbsp;</span>	_ = x[AttrDataMemberLoc-56]
<span id="L49" class="ln">    49&nbsp;&nbsp;</span>	_ = x[AttrDeclColumn-57]
<span id="L50" class="ln">    50&nbsp;&nbsp;</span>	_ = x[AttrDeclFile-58]
<span id="L51" class="ln">    51&nbsp;&nbsp;</span>	_ = x[AttrDeclLine-59]
<span id="L52" class="ln">    52&nbsp;&nbsp;</span>	_ = x[AttrDeclaration-60]
<span id="L53" class="ln">    53&nbsp;&nbsp;</span>	_ = x[AttrDiscrList-61]
<span id="L54" class="ln">    54&nbsp;&nbsp;</span>	_ = x[AttrEncoding-62]
<span id="L55" class="ln">    55&nbsp;&nbsp;</span>	_ = x[AttrExternal-63]
<span id="L56" class="ln">    56&nbsp;&nbsp;</span>	_ = x[AttrFrameBase-64]
<span id="L57" class="ln">    57&nbsp;&nbsp;</span>	_ = x[AttrFriend-65]
<span id="L58" class="ln">    58&nbsp;&nbsp;</span>	_ = x[AttrIdentifierCase-66]
<span id="L59" class="ln">    59&nbsp;&nbsp;</span>	_ = x[AttrMacroInfo-67]
<span id="L60" class="ln">    60&nbsp;&nbsp;</span>	_ = x[AttrNamelistItem-68]
<span id="L61" class="ln">    61&nbsp;&nbsp;</span>	_ = x[AttrPriority-69]
<span id="L62" class="ln">    62&nbsp;&nbsp;</span>	_ = x[AttrSegment-70]
<span id="L63" class="ln">    63&nbsp;&nbsp;</span>	_ = x[AttrSpecification-71]
<span id="L64" class="ln">    64&nbsp;&nbsp;</span>	_ = x[AttrStaticLink-72]
<span id="L65" class="ln">    65&nbsp;&nbsp;</span>	_ = x[AttrType-73]
<span id="L66" class="ln">    66&nbsp;&nbsp;</span>	_ = x[AttrUseLocation-74]
<span id="L67" class="ln">    67&nbsp;&nbsp;</span>	_ = x[AttrVarParam-75]
<span id="L68" class="ln">    68&nbsp;&nbsp;</span>	_ = x[AttrVirtuality-76]
<span id="L69" class="ln">    69&nbsp;&nbsp;</span>	_ = x[AttrVtableElemLoc-77]
<span id="L70" class="ln">    70&nbsp;&nbsp;</span>	_ = x[AttrAllocated-78]
<span id="L71" class="ln">    71&nbsp;&nbsp;</span>	_ = x[AttrAssociated-79]
<span id="L72" class="ln">    72&nbsp;&nbsp;</span>	_ = x[AttrDataLocation-80]
<span id="L73" class="ln">    73&nbsp;&nbsp;</span>	_ = x[AttrStride-81]
<span id="L74" class="ln">    74&nbsp;&nbsp;</span>	_ = x[AttrEntrypc-82]
<span id="L75" class="ln">    75&nbsp;&nbsp;</span>	_ = x[AttrUseUTF8-83]
<span id="L76" class="ln">    76&nbsp;&nbsp;</span>	_ = x[AttrExtension-84]
<span id="L77" class="ln">    77&nbsp;&nbsp;</span>	_ = x[AttrRanges-85]
<span id="L78" class="ln">    78&nbsp;&nbsp;</span>	_ = x[AttrTrampoline-86]
<span id="L79" class="ln">    79&nbsp;&nbsp;</span>	_ = x[AttrCallColumn-87]
<span id="L80" class="ln">    80&nbsp;&nbsp;</span>	_ = x[AttrCallFile-88]
<span id="L81" class="ln">    81&nbsp;&nbsp;</span>	_ = x[AttrCallLine-89]
<span id="L82" class="ln">    82&nbsp;&nbsp;</span>	_ = x[AttrDescription-90]
<span id="L83" class="ln">    83&nbsp;&nbsp;</span>	_ = x[AttrBinaryScale-91]
<span id="L84" class="ln">    84&nbsp;&nbsp;</span>	_ = x[AttrDecimalScale-92]
<span id="L85" class="ln">    85&nbsp;&nbsp;</span>	_ = x[AttrSmall-93]
<span id="L86" class="ln">    86&nbsp;&nbsp;</span>	_ = x[AttrDecimalSign-94]
<span id="L87" class="ln">    87&nbsp;&nbsp;</span>	_ = x[AttrDigitCount-95]
<span id="L88" class="ln">    88&nbsp;&nbsp;</span>	_ = x[AttrPictureString-96]
<span id="L89" class="ln">    89&nbsp;&nbsp;</span>	_ = x[AttrMutable-97]
<span id="L90" class="ln">    90&nbsp;&nbsp;</span>	_ = x[AttrThreadsScaled-98]
<span id="L91" class="ln">    91&nbsp;&nbsp;</span>	_ = x[AttrExplicit-99]
<span id="L92" class="ln">    92&nbsp;&nbsp;</span>	_ = x[AttrObjectPointer-100]
<span id="L93" class="ln">    93&nbsp;&nbsp;</span>	_ = x[AttrEndianity-101]
<span id="L94" class="ln">    94&nbsp;&nbsp;</span>	_ = x[AttrElemental-102]
<span id="L95" class="ln">    95&nbsp;&nbsp;</span>	_ = x[AttrPure-103]
<span id="L96" class="ln">    96&nbsp;&nbsp;</span>	_ = x[AttrRecursive-104]
<span id="L97" class="ln">    97&nbsp;&nbsp;</span>	_ = x[AttrSignature-105]
<span id="L98" class="ln">    98&nbsp;&nbsp;</span>	_ = x[AttrMainSubprogram-106]
<span id="L99" class="ln">    99&nbsp;&nbsp;</span>	_ = x[AttrDataBitOffset-107]
<span id="L100" class="ln">   100&nbsp;&nbsp;</span>	_ = x[AttrConstExpr-108]
<span id="L101" class="ln">   101&nbsp;&nbsp;</span>	_ = x[AttrEnumClass-109]
<span id="L102" class="ln">   102&nbsp;&nbsp;</span>	_ = x[AttrLinkageName-110]
<span id="L103" class="ln">   103&nbsp;&nbsp;</span>	_ = x[AttrStringLengthBitSize-111]
<span id="L104" class="ln">   104&nbsp;&nbsp;</span>	_ = x[AttrStringLengthByteSize-112]
<span id="L105" class="ln">   105&nbsp;&nbsp;</span>	_ = x[AttrRank-113]
<span id="L106" class="ln">   106&nbsp;&nbsp;</span>	_ = x[AttrStrOffsetsBase-114]
<span id="L107" class="ln">   107&nbsp;&nbsp;</span>	_ = x[AttrAddrBase-115]
<span id="L108" class="ln">   108&nbsp;&nbsp;</span>	_ = x[AttrRnglistsBase-116]
<span id="L109" class="ln">   109&nbsp;&nbsp;</span>	_ = x[AttrDwoName-118]
<span id="L110" class="ln">   110&nbsp;&nbsp;</span>	_ = x[AttrReference-119]
<span id="L111" class="ln">   111&nbsp;&nbsp;</span>	_ = x[AttrRvalueReference-120]
<span id="L112" class="ln">   112&nbsp;&nbsp;</span>	_ = x[AttrMacros-121]
<span id="L113" class="ln">   113&nbsp;&nbsp;</span>	_ = x[AttrCallAllCalls-122]
<span id="L114" class="ln">   114&nbsp;&nbsp;</span>	_ = x[AttrCallAllSourceCalls-123]
<span id="L115" class="ln">   115&nbsp;&nbsp;</span>	_ = x[AttrCallAllTailCalls-124]
<span id="L116" class="ln">   116&nbsp;&nbsp;</span>	_ = x[AttrCallReturnPC-125]
<span id="L117" class="ln">   117&nbsp;&nbsp;</span>	_ = x[AttrCallValue-126]
<span id="L118" class="ln">   118&nbsp;&nbsp;</span>	_ = x[AttrCallOrigin-127]
<span id="L119" class="ln">   119&nbsp;&nbsp;</span>	_ = x[AttrCallParameter-128]
<span id="L120" class="ln">   120&nbsp;&nbsp;</span>	_ = x[AttrCallPC-129]
<span id="L121" class="ln">   121&nbsp;&nbsp;</span>	_ = x[AttrCallTailCall-130]
<span id="L122" class="ln">   122&nbsp;&nbsp;</span>	_ = x[AttrCallTarget-131]
<span id="L123" class="ln">   123&nbsp;&nbsp;</span>	_ = x[AttrCallTargetClobbered-132]
<span id="L124" class="ln">   124&nbsp;&nbsp;</span>	_ = x[AttrCallDataLocation-133]
<span id="L125" class="ln">   125&nbsp;&nbsp;</span>	_ = x[AttrCallDataValue-134]
<span id="L126" class="ln">   126&nbsp;&nbsp;</span>	_ = x[AttrNoreturn-135]
<span id="L127" class="ln">   127&nbsp;&nbsp;</span>	_ = x[AttrAlignment-136]
<span id="L128" class="ln">   128&nbsp;&nbsp;</span>	_ = x[AttrExportSymbols-137]
<span id="L129" class="ln">   129&nbsp;&nbsp;</span>	_ = x[AttrDeleted-138]
<span id="L130" class="ln">   130&nbsp;&nbsp;</span>	_ = x[AttrDefaulted-139]
<span id="L131" class="ln">   131&nbsp;&nbsp;</span>	_ = x[AttrLoclistsBase-140]
<span id="L132" class="ln">   132&nbsp;&nbsp;</span>}
<span id="L133" class="ln">   133&nbsp;&nbsp;</span>
<span id="L134" class="ln">   134&nbsp;&nbsp;</span>const _Attr_name = &#34;SiblingLocationNameOrderingByteSizeBitOffsetBitSizeStmtListLowpcHighpcLanguageDiscrDiscrValueVisibilityImportStringLengthCommonRefCompDirConstValueContainingTypeDefaultValueInlineIsOptionalLowerBoundProducerPrototypedReturnAddrStartScopeStrideSizeUpperBoundAbstractOriginAccessibilityAddrClassArtificialBaseTypesCallingCountDataMemberLocDeclColumnDeclFileDeclLineDeclarationDiscrListEncodingExternalFrameBaseFriendIdentifierCaseMacroInfoNamelistItemPrioritySegmentSpecificationStaticLinkTypeUseLocationVarParamVirtualityVtableElemLocAllocatedAssociatedDataLocationStrideEntrypcUseUTF8ExtensionRangesTrampolineCallColumnCallFileCallLineDescriptionBinaryScaleDecimalScaleSmallDecimalSignDigitCountPictureStringMutableThreadsScaledExplicitObjectPointerEndianityElementalPureRecursiveSignatureMainSubprogramDataBitOffsetConstExprEnumClassLinkageNameStringLengthBitSizeStringLengthByteSizeRankStrOffsetsBaseAddrBaseRnglistsBaseDwoNameReferenceRvalueReferenceMacrosCallAllCallsCallAllSourceCallsCallAllTailCallsCallReturnPCCallValueCallOriginCallParameterCallPCCallTailCallCallTargetCallTargetClobberedCallDataLocationCallDataValueNoreturnAlignmentExportSymbolsDeletedDefaultedLoclistsBase&#34;
<span id="L135" class="ln">   135&nbsp;&nbsp;</span>
<span id="L136" class="ln">   136&nbsp;&nbsp;</span>var _Attr_map = map[Attr]string{
<span id="L137" class="ln">   137&nbsp;&nbsp;</span>	1:   _Attr_name[0:7],
<span id="L138" class="ln">   138&nbsp;&nbsp;</span>	2:   _Attr_name[7:15],
<span id="L139" class="ln">   139&nbsp;&nbsp;</span>	3:   _Attr_name[15:19],
<span id="L140" class="ln">   140&nbsp;&nbsp;</span>	9:   _Attr_name[19:27],
<span id="L141" class="ln">   141&nbsp;&nbsp;</span>	11:  _Attr_name[27:35],
<span id="L142" class="ln">   142&nbsp;&nbsp;</span>	12:  _Attr_name[35:44],
<span id="L143" class="ln">   143&nbsp;&nbsp;</span>	13:  _Attr_name[44:51],
<span id="L144" class="ln">   144&nbsp;&nbsp;</span>	16:  _Attr_name[51:59],
<span id="L145" class="ln">   145&nbsp;&nbsp;</span>	17:  _Attr_name[59:64],
<span id="L146" class="ln">   146&nbsp;&nbsp;</span>	18:  _Attr_name[64:70],
<span id="L147" class="ln">   147&nbsp;&nbsp;</span>	19:  _Attr_name[70:78],
<span id="L148" class="ln">   148&nbsp;&nbsp;</span>	21:  _Attr_name[78:83],
<span id="L149" class="ln">   149&nbsp;&nbsp;</span>	22:  _Attr_name[83:93],
<span id="L150" class="ln">   150&nbsp;&nbsp;</span>	23:  _Attr_name[93:103],
<span id="L151" class="ln">   151&nbsp;&nbsp;</span>	24:  _Attr_name[103:109],
<span id="L152" class="ln">   152&nbsp;&nbsp;</span>	25:  _Attr_name[109:121],
<span id="L153" class="ln">   153&nbsp;&nbsp;</span>	26:  _Attr_name[121:130],
<span id="L154" class="ln">   154&nbsp;&nbsp;</span>	27:  _Attr_name[130:137],
<span id="L155" class="ln">   155&nbsp;&nbsp;</span>	28:  _Attr_name[137:147],
<span id="L156" class="ln">   156&nbsp;&nbsp;</span>	29:  _Attr_name[147:161],
<span id="L157" class="ln">   157&nbsp;&nbsp;</span>	30:  _Attr_name[161:173],
<span id="L158" class="ln">   158&nbsp;&nbsp;</span>	32:  _Attr_name[173:179],
<span id="L159" class="ln">   159&nbsp;&nbsp;</span>	33:  _Attr_name[179:189],
<span id="L160" class="ln">   160&nbsp;&nbsp;</span>	34:  _Attr_name[189:199],
<span id="L161" class="ln">   161&nbsp;&nbsp;</span>	37:  _Attr_name[199:207],
<span id="L162" class="ln">   162&nbsp;&nbsp;</span>	39:  _Attr_name[207:217],
<span id="L163" class="ln">   163&nbsp;&nbsp;</span>	42:  _Attr_name[217:227],
<span id="L164" class="ln">   164&nbsp;&nbsp;</span>	44:  _Attr_name[227:237],
<span id="L165" class="ln">   165&nbsp;&nbsp;</span>	46:  _Attr_name[237:247],
<span id="L166" class="ln">   166&nbsp;&nbsp;</span>	47:  _Attr_name[247:257],
<span id="L167" class="ln">   167&nbsp;&nbsp;</span>	49:  _Attr_name[257:271],
<span id="L168" class="ln">   168&nbsp;&nbsp;</span>	50:  _Attr_name[271:284],
<span id="L169" class="ln">   169&nbsp;&nbsp;</span>	51:  _Attr_name[284:293],
<span id="L170" class="ln">   170&nbsp;&nbsp;</span>	52:  _Attr_name[293:303],
<span id="L171" class="ln">   171&nbsp;&nbsp;</span>	53:  _Attr_name[303:312],
<span id="L172" class="ln">   172&nbsp;&nbsp;</span>	54:  _Attr_name[312:319],
<span id="L173" class="ln">   173&nbsp;&nbsp;</span>	55:  _Attr_name[319:324],
<span id="L174" class="ln">   174&nbsp;&nbsp;</span>	56:  _Attr_name[324:337],
<span id="L175" class="ln">   175&nbsp;&nbsp;</span>	57:  _Attr_name[337:347],
<span id="L176" class="ln">   176&nbsp;&nbsp;</span>	58:  _Attr_name[347:355],
<span id="L177" class="ln">   177&nbsp;&nbsp;</span>	59:  _Attr_name[355:363],
<span id="L178" class="ln">   178&nbsp;&nbsp;</span>	60:  _Attr_name[363:374],
<span id="L179" class="ln">   179&nbsp;&nbsp;</span>	61:  _Attr_name[374:383],
<span id="L180" class="ln">   180&nbsp;&nbsp;</span>	62:  _Attr_name[383:391],
<span id="L181" class="ln">   181&nbsp;&nbsp;</span>	63:  _Attr_name[391:399],
<span id="L182" class="ln">   182&nbsp;&nbsp;</span>	64:  _Attr_name[399:408],
<span id="L183" class="ln">   183&nbsp;&nbsp;</span>	65:  _Attr_name[408:414],
<span id="L184" class="ln">   184&nbsp;&nbsp;</span>	66:  _Attr_name[414:428],
<span id="L185" class="ln">   185&nbsp;&nbsp;</span>	67:  _Attr_name[428:437],
<span id="L186" class="ln">   186&nbsp;&nbsp;</span>	68:  _Attr_name[437:449],
<span id="L187" class="ln">   187&nbsp;&nbsp;</span>	69:  _Attr_name[449:457],
<span id="L188" class="ln">   188&nbsp;&nbsp;</span>	70:  _Attr_name[457:464],
<span id="L189" class="ln">   189&nbsp;&nbsp;</span>	71:  _Attr_name[464:477],
<span id="L190" class="ln">   190&nbsp;&nbsp;</span>	72:  _Attr_name[477:487],
<span id="L191" class="ln">   191&nbsp;&nbsp;</span>	73:  _Attr_name[487:491],
<span id="L192" class="ln">   192&nbsp;&nbsp;</span>	74:  _Attr_name[491:502],
<span id="L193" class="ln">   193&nbsp;&nbsp;</span>	75:  _Attr_name[502:510],
<span id="L194" class="ln">   194&nbsp;&nbsp;</span>	76:  _Attr_name[510:520],
<span id="L195" class="ln">   195&nbsp;&nbsp;</span>	77:  _Attr_name[520:533],
<span id="L196" class="ln">   196&nbsp;&nbsp;</span>	78:  _Attr_name[533:542],
<span id="L197" class="ln">   197&nbsp;&nbsp;</span>	79:  _Attr_name[542:552],
<span id="L198" class="ln">   198&nbsp;&nbsp;</span>	80:  _Attr_name[552:564],
<span id="L199" class="ln">   199&nbsp;&nbsp;</span>	81:  _Attr_name[564:570],
<span id="L200" class="ln">   200&nbsp;&nbsp;</span>	82:  _Attr_name[570:577],
<span id="L201" class="ln">   201&nbsp;&nbsp;</span>	83:  _Attr_name[577:584],
<span id="L202" class="ln">   202&nbsp;&nbsp;</span>	84:  _Attr_name[584:593],
<span id="L203" class="ln">   203&nbsp;&nbsp;</span>	85:  _Attr_name[593:599],
<span id="L204" class="ln">   204&nbsp;&nbsp;</span>	86:  _Attr_name[599:609],
<span id="L205" class="ln">   205&nbsp;&nbsp;</span>	87:  _Attr_name[609:619],
<span id="L206" class="ln">   206&nbsp;&nbsp;</span>	88:  _Attr_name[619:627],
<span id="L207" class="ln">   207&nbsp;&nbsp;</span>	89:  _Attr_name[627:635],
<span id="L208" class="ln">   208&nbsp;&nbsp;</span>	90:  _Attr_name[635:646],
<span id="L209" class="ln">   209&nbsp;&nbsp;</span>	91:  _Attr_name[646:657],
<span id="L210" class="ln">   210&nbsp;&nbsp;</span>	92:  _Attr_name[657:669],
<span id="L211" class="ln">   211&nbsp;&nbsp;</span>	93:  _Attr_name[669:674],
<span id="L212" class="ln">   212&nbsp;&nbsp;</span>	94:  _Attr_name[674:685],
<span id="L213" class="ln">   213&nbsp;&nbsp;</span>	95:  _Attr_name[685:695],
<span id="L214" class="ln">   214&nbsp;&nbsp;</span>	96:  _Attr_name[695:708],
<span id="L215" class="ln">   215&nbsp;&nbsp;</span>	97:  _Attr_name[708:715],
<span id="L216" class="ln">   216&nbsp;&nbsp;</span>	98:  _Attr_name[715:728],
<span id="L217" class="ln">   217&nbsp;&nbsp;</span>	99:  _Attr_name[728:736],
<span id="L218" class="ln">   218&nbsp;&nbsp;</span>	100: _Attr_name[736:749],
<span id="L219" class="ln">   219&nbsp;&nbsp;</span>	101: _Attr_name[749:758],
<span id="L220" class="ln">   220&nbsp;&nbsp;</span>	102: _Attr_name[758:767],
<span id="L221" class="ln">   221&nbsp;&nbsp;</span>	103: _Attr_name[767:771],
<span id="L222" class="ln">   222&nbsp;&nbsp;</span>	104: _Attr_name[771:780],
<span id="L223" class="ln">   223&nbsp;&nbsp;</span>	105: _Attr_name[780:789],
<span id="L224" class="ln">   224&nbsp;&nbsp;</span>	106: _Attr_name[789:803],
<span id="L225" class="ln">   225&nbsp;&nbsp;</span>	107: _Attr_name[803:816],
<span id="L226" class="ln">   226&nbsp;&nbsp;</span>	108: _Attr_name[816:825],
<span id="L227" class="ln">   227&nbsp;&nbsp;</span>	109: _Attr_name[825:834],
<span id="L228" class="ln">   228&nbsp;&nbsp;</span>	110: _Attr_name[834:845],
<span id="L229" class="ln">   229&nbsp;&nbsp;</span>	111: _Attr_name[845:864],
<span id="L230" class="ln">   230&nbsp;&nbsp;</span>	112: _Attr_name[864:884],
<span id="L231" class="ln">   231&nbsp;&nbsp;</span>	113: _Attr_name[884:888],
<span id="L232" class="ln">   232&nbsp;&nbsp;</span>	114: _Attr_name[888:902],
<span id="L233" class="ln">   233&nbsp;&nbsp;</span>	115: _Attr_name[902:910],
<span id="L234" class="ln">   234&nbsp;&nbsp;</span>	116: _Attr_name[910:922],
<span id="L235" class="ln">   235&nbsp;&nbsp;</span>	118: _Attr_name[922:929],
<span id="L236" class="ln">   236&nbsp;&nbsp;</span>	119: _Attr_name[929:938],
<span id="L237" class="ln">   237&nbsp;&nbsp;</span>	120: _Attr_name[938:953],
<span id="L238" class="ln">   238&nbsp;&nbsp;</span>	121: _Attr_name[953:959],
<span id="L239" class="ln">   239&nbsp;&nbsp;</span>	122: _Attr_name[959:971],
<span id="L240" class="ln">   240&nbsp;&nbsp;</span>	123: _Attr_name[971:989],
<span id="L241" class="ln">   241&nbsp;&nbsp;</span>	124: _Attr_name[989:1005],
<span id="L242" class="ln">   242&nbsp;&nbsp;</span>	125: _Attr_name[1005:1017],
<span id="L243" class="ln">   243&nbsp;&nbsp;</span>	126: _Attr_name[1017:1026],
<span id="L244" class="ln">   244&nbsp;&nbsp;</span>	127: _Attr_name[1026:1036],
<span id="L245" class="ln">   245&nbsp;&nbsp;</span>	128: _Attr_name[1036:1049],
<span id="L246" class="ln">   246&nbsp;&nbsp;</span>	129: _Attr_name[1049:1055],
<span id="L247" class="ln">   247&nbsp;&nbsp;</span>	130: _Attr_name[1055:1067],
<span id="L248" class="ln">   248&nbsp;&nbsp;</span>	131: _Attr_name[1067:1077],
<span id="L249" class="ln">   249&nbsp;&nbsp;</span>	132: _Attr_name[1077:1096],
<span id="L250" class="ln">   250&nbsp;&nbsp;</span>	133: _Attr_name[1096:1112],
<span id="L251" class="ln">   251&nbsp;&nbsp;</span>	134: _Attr_name[1112:1125],
<span id="L252" class="ln">   252&nbsp;&nbsp;</span>	135: _Attr_name[1125:1133],
<span id="L253" class="ln">   253&nbsp;&nbsp;</span>	136: _Attr_name[1133:1142],
<span id="L254" class="ln">   254&nbsp;&nbsp;</span>	137: _Attr_name[1142:1155],
<span id="L255" class="ln">   255&nbsp;&nbsp;</span>	138: _Attr_name[1155:1162],
<span id="L256" class="ln">   256&nbsp;&nbsp;</span>	139: _Attr_name[1162:1171],
<span id="L257" class="ln">   257&nbsp;&nbsp;</span>	140: _Attr_name[1171:1183],
<span id="L258" class="ln">   258&nbsp;&nbsp;</span>}
<span id="L259" class="ln">   259&nbsp;&nbsp;</span>
<span id="L260" class="ln">   260&nbsp;&nbsp;</span>func (i Attr) String() string {
<span id="L261" class="ln">   261&nbsp;&nbsp;</span>	if str, ok := _Attr_map[i]; ok {
<span id="L262" class="ln">   262&nbsp;&nbsp;</span>		return str
<span id="L263" class="ln">   263&nbsp;&nbsp;</span>	}
<span id="L264" class="ln">   264&nbsp;&nbsp;</span>	return &#34;Attr(&#34; + strconv.FormatInt(int64(i), 10) + &#34;)&#34;
<span id="L265" class="ln">   265&nbsp;&nbsp;</span>}
<span id="L266" class="ln">   266&nbsp;&nbsp;</span>
</pre><p><a href="attr_string.go?m=text">View as plain text</a></p>

<div id="footer">
Build version go1.22.2.<br>
Except as <a href="https://developers.google.com/site-policies#restrictions">noted</a>,
the content of this page is licensed under the
Creative Commons Attribution 3.0 License,
and code is licensed under a <a href="http://localhost:8080/LICENSE">BSD license</a>.<br>
<a href="https://golang.org/doc/tos.html">Terms of Service</a> |
<a href="https://www.google.com/intl/en/policies/privacy/">Privacy Policy</a>
</div>

</div><!-- .container -->
</div><!-- #page -->
</body>
</html>
