<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#375EAB">

  <title>src/os/tempfile.go - Go Documentation Server</title>

<link type="text/css" rel="stylesheet" href="../../lib/godoc/style.css">

<script>window.initFuncs = [];</script>
<script src="../../lib/godoc/jquery.js" defer></script>



<script>var goVersion = "go1.22.2";</script>
<script src="../../lib/godoc/godocs.js" defer></script>
</head>
<body>

<div id='lowframe' style="position: fixed; bottom: 0; left: 0; height: 0; width: 100%; border-top: thin solid grey; background-color: white; overflow: auto;">
...
</div><!-- #lowframe -->

<div id="topbar" class="wide"><div class="container">
<div class="top-heading" id="heading-wide"><a href="../../index.html">Go Documentation Server</a></div>
<div class="top-heading" id="heading-narrow"><a href="../../index.html">GoDoc</a></div>
<a href="tempfile.go#" id="menu-button"><span id="menu-button-arrow">&#9661;</span></a>
<form method="GET" action="http://localhost:8080/search">
<div id="menu">

<span class="search-box"><input type="search" id="search" name="q" placeholder="Search" aria-label="Search" required><button type="submit"><span><!-- magnifying glass: --><svg width="24" height="24" viewBox="0 0 24 24"><title>submit search</title><path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/><path d="M0 0h24v24H0z" fill="none"/></svg></span></button></span>
</div>
</form>

</div></div>



<div id="page" class="wide">
<div class="container">


  <h1>
    Source file
    <a href="http://localhost:8080/src">src</a>/<a href="http://localhost:8080/src/os">os</a>/<span class="text-muted">tempfile.go</span>
  </h1>





  <h2>
    Documentation: <a href="http://localhost:8080/pkg/os">os</a>
  </h2>



<div id="nav"></div>


<script type='text/javascript'>document.ANALYSIS_DATA = null;</script>
<pre><span id="L1" class="ln">     1&nbsp;&nbsp;</span><span class="comment">// Copyright 2010 The Go Authors. All rights reserved.</span>
<span id="L2" class="ln">     2&nbsp;&nbsp;</span><span class="comment">// Use of this source code is governed by a BSD-style</span>
<span id="L3" class="ln">     3&nbsp;&nbsp;</span><span class="comment">// license that can be found in the LICENSE file.</span>
<span id="L4" class="ln">     4&nbsp;&nbsp;</span>
<span id="L5" class="ln">     5&nbsp;&nbsp;</span>package os
<span id="L6" class="ln">     6&nbsp;&nbsp;</span>
<span id="L7" class="ln">     7&nbsp;&nbsp;</span>import (
<span id="L8" class="ln">     8&nbsp;&nbsp;</span>	&#34;errors&#34;
<span id="L9" class="ln">     9&nbsp;&nbsp;</span>	&#34;internal/bytealg&#34;
<span id="L10" class="ln">    10&nbsp;&nbsp;</span>	&#34;internal/itoa&#34;
<span id="L11" class="ln">    11&nbsp;&nbsp;</span>	_ &#34;unsafe&#34; <span class="comment">// for go:linkname</span>
<span id="L12" class="ln">    12&nbsp;&nbsp;</span>)
<span id="L13" class="ln">    13&nbsp;&nbsp;</span>
<span id="L14" class="ln">    14&nbsp;&nbsp;</span><span class="comment">// random number source provided by runtime.</span>
<span id="L15" class="ln">    15&nbsp;&nbsp;</span><span class="comment">// We generate random temporary file names so that there&#39;s a good</span>
<span id="L16" class="ln">    16&nbsp;&nbsp;</span><span class="comment">// chance the file doesn&#39;t exist yet - keeps the number of tries in</span>
<span id="L17" class="ln">    17&nbsp;&nbsp;</span><span class="comment">// TempFile to a minimum.</span>
<span id="L18" class="ln">    18&nbsp;&nbsp;</span><span class="comment">//go:linkname runtime_rand runtime.rand</span>
<span id="L19" class="ln">    19&nbsp;&nbsp;</span>func runtime_rand() uint64
<span id="L20" class="ln">    20&nbsp;&nbsp;</span>
<span id="L21" class="ln">    21&nbsp;&nbsp;</span>func nextRandom() string {
<span id="L22" class="ln">    22&nbsp;&nbsp;</span>	return itoa.Uitoa(uint(uint32(runtime_rand())))
<span id="L23" class="ln">    23&nbsp;&nbsp;</span>}
<span id="L24" class="ln">    24&nbsp;&nbsp;</span>
<span id="L25" class="ln">    25&nbsp;&nbsp;</span><span class="comment">// CreateTemp creates a new temporary file in the directory dir,</span>
<span id="L26" class="ln">    26&nbsp;&nbsp;</span><span class="comment">// opens the file for reading and writing, and returns the resulting file.</span>
<span id="L27" class="ln">    27&nbsp;&nbsp;</span><span class="comment">// The filename is generated by taking pattern and adding a random string to the end.</span>
<span id="L28" class="ln">    28&nbsp;&nbsp;</span><span class="comment">// If pattern includes a &#34;*&#34;, the random string replaces the last &#34;*&#34;.</span>
<span id="L29" class="ln">    29&nbsp;&nbsp;</span><span class="comment">// If dir is the empty string, CreateTemp uses the default directory for temporary files, as returned by TempDir.</span>
<span id="L30" class="ln">    30&nbsp;&nbsp;</span><span class="comment">// Multiple programs or goroutines calling CreateTemp simultaneously will not choose the same file.</span>
<span id="L31" class="ln">    31&nbsp;&nbsp;</span><span class="comment">// The caller can use the file&#39;s Name method to find the pathname of the file.</span>
<span id="L32" class="ln">    32&nbsp;&nbsp;</span><span class="comment">// It is the caller&#39;s responsibility to remove the file when it is no longer needed.</span>
<span id="L33" class="ln">    33&nbsp;&nbsp;</span>func CreateTemp(dir, pattern string) (*File, error) {
<span id="L34" class="ln">    34&nbsp;&nbsp;</span>	if dir == &#34;&#34; {
<span id="L35" class="ln">    35&nbsp;&nbsp;</span>		dir = TempDir()
<span id="L36" class="ln">    36&nbsp;&nbsp;</span>	}
<span id="L37" class="ln">    37&nbsp;&nbsp;</span>
<span id="L38" class="ln">    38&nbsp;&nbsp;</span>	prefix, suffix, err := prefixAndSuffix(pattern)
<span id="L39" class="ln">    39&nbsp;&nbsp;</span>	if err != nil {
<span id="L40" class="ln">    40&nbsp;&nbsp;</span>		return nil, &amp;PathError{Op: &#34;createtemp&#34;, Path: pattern, Err: err}
<span id="L41" class="ln">    41&nbsp;&nbsp;</span>	}
<span id="L42" class="ln">    42&nbsp;&nbsp;</span>	prefix = joinPath(dir, prefix)
<span id="L43" class="ln">    43&nbsp;&nbsp;</span>
<span id="L44" class="ln">    44&nbsp;&nbsp;</span>	try := 0
<span id="L45" class="ln">    45&nbsp;&nbsp;</span>	for {
<span id="L46" class="ln">    46&nbsp;&nbsp;</span>		name := prefix + nextRandom() + suffix
<span id="L47" class="ln">    47&nbsp;&nbsp;</span>		f, err := OpenFile(name, O_RDWR|O_CREATE|O_EXCL, 0600)
<span id="L48" class="ln">    48&nbsp;&nbsp;</span>		if IsExist(err) {
<span id="L49" class="ln">    49&nbsp;&nbsp;</span>			if try++; try &lt; 10000 {
<span id="L50" class="ln">    50&nbsp;&nbsp;</span>				continue
<span id="L51" class="ln">    51&nbsp;&nbsp;</span>			}
<span id="L52" class="ln">    52&nbsp;&nbsp;</span>			return nil, &amp;PathError{Op: &#34;createtemp&#34;, Path: prefix + &#34;*&#34; + suffix, Err: ErrExist}
<span id="L53" class="ln">    53&nbsp;&nbsp;</span>		}
<span id="L54" class="ln">    54&nbsp;&nbsp;</span>		return f, err
<span id="L55" class="ln">    55&nbsp;&nbsp;</span>	}
<span id="L56" class="ln">    56&nbsp;&nbsp;</span>}
<span id="L57" class="ln">    57&nbsp;&nbsp;</span>
<span id="L58" class="ln">    58&nbsp;&nbsp;</span>var errPatternHasSeparator = errors.New(&#34;pattern contains path separator&#34;)
<span id="L59" class="ln">    59&nbsp;&nbsp;</span>
<span id="L60" class="ln">    60&nbsp;&nbsp;</span><span class="comment">// prefixAndSuffix splits pattern by the last wildcard &#34;*&#34;, if applicable,</span>
<span id="L61" class="ln">    61&nbsp;&nbsp;</span><span class="comment">// returning prefix as the part before &#34;*&#34; and suffix as the part after &#34;*&#34;.</span>
<span id="L62" class="ln">    62&nbsp;&nbsp;</span>func prefixAndSuffix(pattern string) (prefix, suffix string, err error) {
<span id="L63" class="ln">    63&nbsp;&nbsp;</span>	for i := 0; i &lt; len(pattern); i++ {
<span id="L64" class="ln">    64&nbsp;&nbsp;</span>		if IsPathSeparator(pattern[i]) {
<span id="L65" class="ln">    65&nbsp;&nbsp;</span>			return &#34;&#34;, &#34;&#34;, errPatternHasSeparator
<span id="L66" class="ln">    66&nbsp;&nbsp;</span>		}
<span id="L67" class="ln">    67&nbsp;&nbsp;</span>	}
<span id="L68" class="ln">    68&nbsp;&nbsp;</span>	if pos := bytealg.LastIndexByteString(pattern, &#39;*&#39;); pos != -1 {
<span id="L69" class="ln">    69&nbsp;&nbsp;</span>		prefix, suffix = pattern[:pos], pattern[pos+1:]
<span id="L70" class="ln">    70&nbsp;&nbsp;</span>	} else {
<span id="L71" class="ln">    71&nbsp;&nbsp;</span>		prefix = pattern
<span id="L72" class="ln">    72&nbsp;&nbsp;</span>	}
<span id="L73" class="ln">    73&nbsp;&nbsp;</span>	return prefix, suffix, nil
<span id="L74" class="ln">    74&nbsp;&nbsp;</span>}
<span id="L75" class="ln">    75&nbsp;&nbsp;</span>
<span id="L76" class="ln">    76&nbsp;&nbsp;</span><span class="comment">// MkdirTemp creates a new temporary directory in the directory dir</span>
<span id="L77" class="ln">    77&nbsp;&nbsp;</span><span class="comment">// and returns the pathname of the new directory.</span>
<span id="L78" class="ln">    78&nbsp;&nbsp;</span><span class="comment">// The new directory&#39;s name is generated by adding a random string to the end of pattern.</span>
<span id="L79" class="ln">    79&nbsp;&nbsp;</span><span class="comment">// If pattern includes a &#34;*&#34;, the random string replaces the last &#34;*&#34; instead.</span>
<span id="L80" class="ln">    80&nbsp;&nbsp;</span><span class="comment">// If dir is the empty string, MkdirTemp uses the default directory for temporary files, as returned by TempDir.</span>
<span id="L81" class="ln">    81&nbsp;&nbsp;</span><span class="comment">// Multiple programs or goroutines calling MkdirTemp simultaneously will not choose the same directory.</span>
<span id="L82" class="ln">    82&nbsp;&nbsp;</span><span class="comment">// It is the caller&#39;s responsibility to remove the directory when it is no longer needed.</span>
<span id="L83" class="ln">    83&nbsp;&nbsp;</span>func MkdirTemp(dir, pattern string) (string, error) {
<span id="L84" class="ln">    84&nbsp;&nbsp;</span>	if dir == &#34;&#34; {
<span id="L85" class="ln">    85&nbsp;&nbsp;</span>		dir = TempDir()
<span id="L86" class="ln">    86&nbsp;&nbsp;</span>	}
<span id="L87" class="ln">    87&nbsp;&nbsp;</span>
<span id="L88" class="ln">    88&nbsp;&nbsp;</span>	prefix, suffix, err := prefixAndSuffix(pattern)
<span id="L89" class="ln">    89&nbsp;&nbsp;</span>	if err != nil {
<span id="L90" class="ln">    90&nbsp;&nbsp;</span>		return &#34;&#34;, &amp;PathError{Op: &#34;mkdirtemp&#34;, Path: pattern, Err: err}
<span id="L91" class="ln">    91&nbsp;&nbsp;</span>	}
<span id="L92" class="ln">    92&nbsp;&nbsp;</span>	prefix = joinPath(dir, prefix)
<span id="L93" class="ln">    93&nbsp;&nbsp;</span>
<span id="L94" class="ln">    94&nbsp;&nbsp;</span>	try := 0
<span id="L95" class="ln">    95&nbsp;&nbsp;</span>	for {
<span id="L96" class="ln">    96&nbsp;&nbsp;</span>		name := prefix + nextRandom() + suffix
<span id="L97" class="ln">    97&nbsp;&nbsp;</span>		err := Mkdir(name, 0700)
<span id="L98" class="ln">    98&nbsp;&nbsp;</span>		if err == nil {
<span id="L99" class="ln">    99&nbsp;&nbsp;</span>			return name, nil
<span id="L100" class="ln">   100&nbsp;&nbsp;</span>		}
<span id="L101" class="ln">   101&nbsp;&nbsp;</span>		if IsExist(err) {
<span id="L102" class="ln">   102&nbsp;&nbsp;</span>			if try++; try &lt; 10000 {
<span id="L103" class="ln">   103&nbsp;&nbsp;</span>				continue
<span id="L104" class="ln">   104&nbsp;&nbsp;</span>			}
<span id="L105" class="ln">   105&nbsp;&nbsp;</span>			return &#34;&#34;, &amp;PathError{Op: &#34;mkdirtemp&#34;, Path: dir + string(PathSeparator) + prefix + &#34;*&#34; + suffix, Err: ErrExist}
<span id="L106" class="ln">   106&nbsp;&nbsp;</span>		}
<span id="L107" class="ln">   107&nbsp;&nbsp;</span>		if IsNotExist(err) {
<span id="L108" class="ln">   108&nbsp;&nbsp;</span>			if _, err := Stat(dir); IsNotExist(err) {
<span id="L109" class="ln">   109&nbsp;&nbsp;</span>				return &#34;&#34;, err
<span id="L110" class="ln">   110&nbsp;&nbsp;</span>			}
<span id="L111" class="ln">   111&nbsp;&nbsp;</span>		}
<span id="L112" class="ln">   112&nbsp;&nbsp;</span>		return &#34;&#34;, err
<span id="L113" class="ln">   113&nbsp;&nbsp;</span>	}
<span id="L114" class="ln">   114&nbsp;&nbsp;</span>}
<span id="L115" class="ln">   115&nbsp;&nbsp;</span>
<span id="L116" class="ln">   116&nbsp;&nbsp;</span>func joinPath(dir, name string) string {
<span id="L117" class="ln">   117&nbsp;&nbsp;</span>	if len(dir) &gt; 0 &amp;&amp; IsPathSeparator(dir[len(dir)-1]) {
<span id="L118" class="ln">   118&nbsp;&nbsp;</span>		return dir + name
<span id="L119" class="ln">   119&nbsp;&nbsp;</span>	}
<span id="L120" class="ln">   120&nbsp;&nbsp;</span>	return dir + string(PathSeparator) + name
<span id="L121" class="ln">   121&nbsp;&nbsp;</span>}
<span id="L122" class="ln">   122&nbsp;&nbsp;</span>
</pre><p><a href="tempfile.go?m=text">View as plain text</a></p>

<div id="footer">
Build version go1.22.2.<br>
Except as <a href="https://developers.google.com/site-policies#restrictions">noted</a>,
the content of this page is licensed under the
Creative Commons Attribution 3.0 License,
and code is licensed under a <a href="http://localhost:8080/LICENSE">BSD license</a>.<br>
<a href="https://golang.org/doc/tos.html">Terms of Service</a> |
<a href="https://www.google.com/intl/en/policies/privacy/">Privacy Policy</a>
</div>

</div><!-- .container -->
</div><!-- #page -->
</body>
</html>
