package middleware

import (
	"backend/config"
	"backend/utils/database"
	"backend/utils/jwt"
	"database/sql"
	"log"
	"net/http"
	"time"
)

func Authenticate(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		db := database.GetDb()
		now := time.Now()

		/* Check whether access token was passed in the request. */
		accessCookie, err := r.Cookie("access_token")
		if err == http.ErrNoCookie {
			log.Println(err)
			w.WriteHeader(http.StatusUnauthorized)
			return
		} else if err != nil {
			log.Printf("error while trying to retrieve the access token: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}

		/* Check whether refresh token was passed in the request. */
		refreshCookie, err := r.Cookie("refresh_token")
		if err == http.ErrNoCookie {
			log.Println(err)
			w.WriteHeader(http.StatusUnauthorized)
			return
		} else if err != nil {
			log.Printf("error while trying to retrieve the refresh token: %v", err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}

		accessToken := accessCookie.Value
		refreshToken := refreshCookie.Value

		/* Check whether the tokens were actually generated by the server */
		if !jwt.WasGeneratedWithSecret(refreshToken, config.JwtSecret) || !jwt.WasGeneratedWithSecret(accessToken, config.JwtSecret) {
			log.Println("Token wasn't generated here")
			w.WriteHeader(http.StatusUnauthorized)
			return
		}

		claimsRefresh, err := jwt.DecodePayload(refreshToken)
		if err != nil {
			log.Println(err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}

		claimsAccess, err := jwt.DecodePayload(accessToken)
		if err != nil {
			log.Println(err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}

		/* Check whether the refresh token has expired. If it has, delete the cookies and reply with 401.*/
		expiresRefresh := int64(claimsRefresh["exp"].(float64))
		if expiresRefresh < now.Unix() {
			if err := db.DeleteRefreshTokenByToken(refreshToken); err != nil {
				log.Println(err)
				w.WriteHeader(http.StatusInternalServerError)
				return
			}

			http.SetCookie(w, &http.Cookie{
				Name:     "refresh_token",
				Value:    "",
				HttpOnly: true,
				Path:     "/",
				Expires:  time.Unix(0, 0),
			})

			http.SetCookie(w, &http.Cookie{
				Name:     "access_token",
				Value:    "",
				HttpOnly: true,
				Path:     "/",
				Expires:  time.Unix(0, 0),
			})

			w.WriteHeader(http.StatusUnauthorized)
			return
		}

		/* Check whether refresh token is assigned to the right person (db). */
		userId := claimsRefresh["user"].(string)
		tk, err := db.GetRefreshTokenByUserId(userId)
		if err == sql.ErrNoRows {
			w.WriteHeader(http.StatusUnauthorized)
			return
		} else if err != nil {
			log.Println(err)
			w.WriteHeader(http.StatusInternalServerError)
			return
		}

		if tk.UserId != userId {
			w.WriteHeader(http.StatusUnauthorized)
			return
		}

		/* Check whether the access token has expired, if it has, issue another one. */
		expiresAccess := int64(claimsAccess["exp"].(float64))
		if expiresAccess < now.Unix() {
			user, err := db.GetUserById(claimsAccess["user"].(string))
			if err != nil {
				log.Println(err)
				w.WriteHeader(http.StatusInternalServerError)
				return
			}

			access, err := jwt.GenerateAccessToken(user, now)
			if err != nil {
				log.Println(err)
				w.WriteHeader(http.StatusInternalServerError)
				return
			}

			http.SetCookie(w, &http.Cookie{
				Name:     "access_token",
				Value:    access,
				HttpOnly: true,
				Path:     "/",
				Expires:  now.Add(time.Duration(config.JwtAccExpTime)),
			})
		}

		next(w, r)
	}
}
