name: Backend API Deployment

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.2"

      - name: Build the application
        run: |
          cd src
          go build -o ../bin/lumina-backend

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Create directories on server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST 'sudo mkdir -p /home/$SERVER_USER/lumina-back-end/src && sudo mkdir -p /home/$SERVER_USER/lumina-back-end/bin'

      - name: Deploy to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          scp -P $SERVER_PORT -r * $SERVER_USER@$SERVER_HOST:/home/$SERVER_USER/lumina-back-end

      - name: Build on server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST 'cd /home/$SERVER_USER/lumina-back-end/src && go build -o ../bin/lumina-backend'
