name: Backend API Build & Deploy

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.2"

      - name: Build the application
        run: |
          cd src
          go build -o ../bin/lumina-backend

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          scp -P $SERVER_PORT bin/lumina-backend $SERVER_USER@$SERVER_HOST:/lumina-back-end
          ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST 'sudo systemctl restart lumina-back-end'
